# Generated by Django 4.2.25 on 2026-02-10 12:05

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_organization_enforce_department_isolation'),
        ('revenue', '0004_add_penalty_waiver_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='District Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='District Code')),
                ('province', models.CharField(default='Khyber Pakhtunkhwa', max_length=100, verbose_name='Province')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mauza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('name', models.CharField(max_length=200, verbose_name='Mauza Name')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Mauza Code')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mauzas', to='property.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'Mauza',
                'verbose_name_plural': 'Mauzas',
                'ordering': ['district__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('property_code', models.CharField(help_text='Unique identifier (e.g., PSH-COM-001)', max_length=50, unique=True, verbose_name='Property Code')),
                ('name', models.CharField(help_text='e.g., Shop No. 1-A, House 123', max_length=200, verbose_name='Property Name')),
                ('property_type', models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('RESIDENTIAL', 'Residential'), ('INDUSTRIAL', 'Industrial'), ('AGRICULTURAL', 'Agricultural'), ('INSTITUTIONAL', 'Institutional'), ('MIXED_USE', 'Mixed Use')], default='COMMERCIAL', max_length=20, verbose_name='Property Type')),
                ('property_sub_type', models.CharField(choices=[('SHOP', 'Shop'), ('PLAZA', 'Plaza/Building'), ('OFFICE', 'Office'), ('WAREHOUSE', 'Warehouse'), ('MARKET', 'Market'), ('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('FLAT', 'Flat'), ('PLOT', 'Vacant Plot'), ('LAND', 'Agricultural Land'), ('PARKING', 'Parking Space'), ('OTHER', 'Other')], default='SHOP', max_length=20, verbose_name='Property Sub-Type')),
                ('status', models.CharField(choices=[('RENTED_OUT', 'Rented Out'), ('VACANT', 'Vacant'), ('SELF_USE', 'Self Use (TMA)'), ('UNDER_LITIGATION', 'Under Litigation'), ('UNDER_CONSTRUCTION', 'Under Construction'), ('DEMOLISHED', 'Demolished'), ('ENCROACHED', 'Encroached')], default='VACANT', max_length=30, verbose_name='Property Status')),
                ('address', models.TextField(verbose_name='Complete Address')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='GPS Latitude (e.g., 34.0082744)', max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, help_text='GPS Longitude (e.g., 71.5731692)', max_digits=10, verbose_name='Longitude')),
                ('area_marlas', models.DecimalField(decimal_places=4, help_text='1 Marla = 225 sq.ft = 20.9 sq.m', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Area (Marlas)')),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Auto-calculated from Marlas', max_digits=12, null=True, verbose_name='Area (Sq.Ft)')),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Auto-calculated from Marlas', max_digits=12, null=True, verbose_name='Area (Sq.M)')),
                ('ownership_title', models.CharField(help_text='As per land revenue record', max_length=500, verbose_name='Ownership Title')),
                ('survey_number', models.CharField(blank=True, max_length=100, verbose_name='Survey/Khasra Number')),
                ('annual_rent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual rent amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Annual Rent')),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Auto-calculated (Annual / 12)', max_digits=15, null=True, verbose_name='Monthly Rent')),
                ('last_rent_revision', models.DateField(blank=True, null=True, verbose_name='Last Rent Revision Date')),
                ('tenant_name', models.CharField(blank=True, help_text='If tenant not in system', max_length=200, verbose_name='Tenant Name')),
                ('tenant_cnic', models.CharField(blank=True, max_length=20, verbose_name='Tenant CNIC')),
                ('tenant_contact', models.CharField(blank=True, max_length=20, verbose_name='Tenant Contact')),
                ('lease_start_date', models.DateField(blank=True, null=True, verbose_name='Lease Start Date')),
                ('lease_end_date', models.DateField(blank=True, null=True, verbose_name='Lease End Date')),
                ('court_case_status', models.CharField(choices=[('NO_CASE', 'No Case'), ('PENDING', 'Case Pending'), ('DECIDED_FAVOR', 'Decided in Favor'), ('DECIDED_AGAINST', 'Decided Against'), ('UNDER_APPEAL', 'Under Appeal')], default='NO_CASE', max_length=20, verbose_name='Court Case Status')),
                ('court_case_title', models.CharField(blank=True, max_length=500, verbose_name='Case Title/Description')),
                ('court_name', models.CharField(blank=True, max_length=200, verbose_name='Name of Court')),
                ('case_number', models.CharField(blank=True, max_length=100, verbose_name='Court Case Number')),
                ('next_hearing_date', models.DateField(blank=True, null=True, verbose_name='Next Hearing Date')),
                ('future_use', models.TextField(blank=True, verbose_name='Future Use/Plans')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks/Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('current_tenant', models.ForeignKey(blank=True, help_text='Link to Payer in revenue module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_properties', to='revenue.payer', verbose_name='Current Tenant')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='property.district', verbose_name='District')),
                ('mauza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='property.mauza', verbose_name='Mauza/Revenue Estate')),
                ('organization', models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('name', models.CharField(max_length=200, verbose_name='Village/Neighbourhood Name')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Village Code')),
                ('mauza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villages', to='property.mauza', verbose_name='Mauza')),
            ],
            options={
                'verbose_name': 'Village/Neighbourhood',
                'verbose_name_plural': 'Villages/Neighbourhoods',
                'ordering': ['mauza__name', 'name'],
                'unique_together': {('name', 'mauza')},
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('photo', models.ImageField(upload_to='property_photos/%Y/%m/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('photo_url', models.URLField(blank=True, help_text='Google Drive or external photo URL', max_length=500, verbose_name='Photo URL')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Photo')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='property.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property Photo',
                'verbose_name_plural': 'Property Photos',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('action', models.CharField(help_text='e.g., Created, Updated, Status Changed', max_length=50, verbose_name='Action')),
                ('field_changed', models.CharField(blank=True, max_length=100, verbose_name='Field Changed')),
                ('old_value', models.TextField(blank=True, verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, verbose_name='New Value')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='property.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property History',
                'verbose_name_plural': 'Property History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('document_type', models.CharField(help_text='e.g., Rent Agreement, Ownership Deed, Court Order', max_length=100, verbose_name='Document Type')),
                ('document', models.FileField(upload_to='property_docs/%Y/%m/', verbose_name='Document')),
                ('document_url', models.URLField(blank=True, help_text='Google Drive or external document URL', max_length=500, verbose_name='Document URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='property.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property Document',
                'verbose_name_plural': 'Property Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='property.village', verbose_name='Village/Neighbourhood'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_code'], name='property_pr_propert_732a98_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='property_pr_status_b98bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='property_pr_propert_01098c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['district', 'mauza'], name='property_pr_distric_0f6a72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mauza',
            unique_together={('name', 'district')},
        ),
    ]
