# Generated by Django 4.2.25 on 2026-02-10 12:56

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organization_enforce_department_isolation'),
        ('revenue', '0004_add_penalty_waiver_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('lease_number', models.CharField(help_text='Unique lease reference (e.g., LEASE-2026-001)', max_length=50, unique=True, verbose_name='Lease Agreement Number')),
                ('lease_start_date', models.DateField(verbose_name='Lease Start Date')),
                ('lease_end_date', models.DateField(blank=True, help_text='Leave blank for month-to-month tenancy', null=True, verbose_name='Lease End Date')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monthly Rent Amount')),
                ('security_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Advance/security deposit amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Security Deposit')),
                ('annual_increment_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual rent increase percentage', max_digits=5, verbose_name='Annual Increment (%)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('RENEWED', 'Renewed')], default='DRAFT', max_length=15, verbose_name='Lease Status')),
                ('agreement_date', models.DateField(blank=True, null=True, verbose_name='Agreement Signed Date')),
                ('agreement_document', models.FileField(blank=True, null=True, upload_to='lease_agreements/%Y/%m/', verbose_name='Agreement Document')),
                ('termination_date', models.DateField(blank=True, help_text='Actual date lease was terminated', null=True, verbose_name='Termination Date')),
                ('termination_reason', models.TextField(blank=True, verbose_name='Termination Reason')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='Terms & Conditions')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Property Lease',
                'verbose_name_plural': 'Property Leases',
                'ordering': ['-lease_start_date', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='current_tenant',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lease_end_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lease_start_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='tenant_cnic',
        ),
        migrations.RemoveField(
            model_name='property',
            name='tenant_contact',
        ),
        migrations.RemoveField(
            model_name='property',
            name='tenant_name',
        ),
        migrations.AlterField(
            model_name='mauza',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_mauzas', to='core.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='core.district', verbose_name='District'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.AddField(
            model_name='propertylease',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='property.property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='propertylease',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant from Payer registry', on_delete=django.db.models.deletion.PROTECT, related_name='property_leases', to='revenue.payer', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='propertylease',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddIndex(
            model_name='propertylease',
            index=models.Index(fields=['lease_number'], name='property_pr_lease_n_a60886_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylease',
            index=models.Index(fields=['property', 'status'], name='property_pr_propert_349e51_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylease',
            index=models.Index(fields=['tenant', 'status'], name='property_pr_tenant__a8be03_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylease',
            index=models.Index(fields=['lease_start_date', 'lease_end_date'], name='property_pr_lease_s_a0866b_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertylease',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('property', 'status'), name='unique_active_lease_per_property'),
        ),
    ]
