# Generated by Django 4.2.25 on 2026-02-10 13:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertylease_remove_property_current_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='acquisition_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original cost when acquired by TMA', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Acquisition Cost'),
        ),
        migrations.AddField(
            model_name='property',
            name='acquisition_date',
            field=models.DateField(blank=True, help_text='Date when property was acquired by TMA', null=True, verbose_name='Acquisition Date'),
        ),
        migrations.AddField(
            model_name='property',
            name='current_market_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current estimated market value', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Current Market Value'),
        ),
        migrations.AddField(
            model_name='property',
            name='last_valuation_date',
            field=models.DateField(blank=True, help_text='Date of last property valuation', null=True, verbose_name='Last Valuation Date'),
        ),
    ]
