# Generated by Django 4.2.25 on 2026-02-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_acquisition_cost_property_acquisition_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='document_type',
            field=models.CharField(choices=[('LEASE_AGREEMENT', 'Lease Agreement'), ('RENT_AGREEMENT', 'Rent Agreement'), ('OWNERSHIP_DEED', 'Ownership Deed'), ('TRANSFER_DEED', 'Transfer Deed'), ('ALLOTMENT_LETTER', 'Allotment Letter'), ('SURVEY_REPORT', 'Survey Report'), ('VALUATION_REPORT', 'Valuation Report'), ('TAX_RECORD', 'Tax Record'), ('COURT_ORDER', 'Court Order'), ('LEGAL_NOTICE', 'Legal Notice'), ('MAINTENANCE_RECORD', 'Maintenance Record'), ('INSURANCE_POLICY', 'Insurance Policy'), ('OTHER', 'Other Document')], max_length=100, verbose_name='Document Type'),
        ),
    ]
