# Generated by Django 4.2.25 on 2026-02-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_propertydocument_document_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['latitude', 'longitude'], name='property_pr_latitud_2c331f_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['annual_rent'], name='property_pr_annual__0d40e7_idx'),
        ),
    ]
