# Generated by Django 6.0.1 on 2026-01-24 16:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code for the function (e.g., AD, WS, SW).', max_length=10, unique=True, verbose_name='Function Code')),
                ('name', models.CharField(help_text='Full name of the function (e.g., Administration).', max_length=100, verbose_name='Function Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Function Code',
                'verbose_name_plural': 'Function Codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BudgetHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active in the system.', verbose_name='Is Active')),
                ('fund_id', models.PositiveSmallIntegerField(default=1, help_text='1=Current, 2=Development, 4=PLA, 5=Pension', verbose_name='Fund ID')),
                ('pifra_object', models.CharField(help_text='Standard PIFRA object code (e.g., A01101).', max_length=20, validators=[django.core.validators.RegexValidator(message='NAM code must be alphanumeric (e.g., A01101 or A01101-000).', regex='^[A-Z0-9]+-?[A-Z0-9]*$')], verbose_name='PIFRA Object Code')),
                ('pifra_description', models.CharField(help_text='Standard PIFRA description.', max_length=255, verbose_name='PIFRA Description')),
                ('tma_sub_object', models.CharField(help_text='TMA-specific sub-object code (e.g., A01101-000).', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='NAM code must be alphanumeric (e.g., A01101 or A01101-000).', regex='^[A-Z0-9]+-?[A-Z0-9]*$')], verbose_name='TMA Sub-Object Code')),
                ('tma_description', models.CharField(help_text='TMA-specific description.', max_length=255, verbose_name='TMA Description')),
                ('account_type', models.CharField(choices=[('EXP', 'Expenditure'), ('REV', 'Revenue'), ('LIA', 'Liability'), ('AST', 'Asset'), ('EQT', 'Equity')], default='EXP', max_length=3, verbose_name='Account Type')),
                ('fund_type', models.CharField(choices=[('PUGF', 'PUGF (Provincial)'), ('NPUGF', 'Non-PUGF (Local)'), ('DEV', 'Development'), ('PEN', 'Pension'), ('OTH', 'Other')], default='NPUGF', help_text='PUGF/Non-PUGF classification (derived from object code).', max_length=5, verbose_name='Fund Type')),
                ('budget_control', models.BooleanField(default=True, help_text='Whether hard budget limits are enforced.', verbose_name='Budget Control')),
                ('project_required', models.BooleanField(default=False, help_text='Whether a project code is required for transactions.', verbose_name='Project Required')),
                ('posting_allowed', models.BooleanField(default=True, help_text='Whether transactions can be posted to this head.', verbose_name='Posting Allowed')),
                ('is_charged', models.BooleanField(default=False, help_text='Charged expenditure that Council cannot reduce.', verbose_name='Is Charged (Non-Votable)')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_heads', to='finance.functioncode', verbose_name='Function')),
            ],
            options={
                'verbose_name': 'Budget Head',
                'verbose_name_plural': 'Budget Heads',
                'ordering': ['fund_id', 'pifra_object', 'tma_sub_object'],
                'indexes': [models.Index(fields=['pifra_object'], name='finance_bud_pifra_o_7c2fcb_idx'), models.Index(fields=['tma_sub_object'], name='finance_bud_tma_sub_cda0aa_idx'), models.Index(fields=['fund_type'], name='finance_bud_fund_ty_e2a06d_idx'), models.Index(fields=['account_type'], name='finance_bud_account_13a1b8_idx')],
            },
        ),
    ]
