# Generated by Django 6.0.1 on 2026-01-24 19:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgethead',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', null=True, verbose_name='Public ID'),
        ),
        migrations.AddField(
            model_name='functioncode',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', null=True, verbose_name='Public ID'),
        ),
    ]
