# Generated by Django 4.2.25 on 2026-01-26 18:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_remove_organization_bank_account_no_and_more'),
        ('budgeting', '0010_update_bps_salary_structure'),
        ('finance', '0003_alter_budgethead_public_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('name', models.CharField(help_text='Name of the fund (e.g., "General", "Development", "Pension").', max_length=100, unique=True, verbose_name='Fund Name')),
                ('code', models.CharField(help_text='Short code for the fund (e.g., "GEN", "DEV", "PEN").', max_length=10, unique=True, verbose_name='Fund Code')),
                ('description', models.TextField(blank=True, help_text='Detailed description of fund purpose.', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Fund',
                'verbose_name_plural': 'Funds',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('voucher_no', models.CharField(help_text='Unique voucher number (e.g., "JV-2026-001").', max_length=50, verbose_name='Voucher Number')),
                ('date', models.DateField(help_text='Date of the transaction.', verbose_name='Transaction Date')),
                ('voucher_type', models.CharField(choices=[('JV', 'Journal Voucher'), ('PV', 'Payment Voucher'), ('RV', 'Receipt Voucher')], default='JV', max_length=2, verbose_name='Voucher Type')),
                ('description', models.TextField(help_text='Narration/explanation of the transaction.', verbose_name='Description')),
                ('is_posted', models.BooleanField(default=False, help_text='Whether this voucher has been posted to the General Ledger.', verbose_name='Is Posted')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='budgeting.fiscalyear', verbose_name='Fiscal Year')),
                ('fund', models.ForeignKey(help_text='Fund classification for this transaction.', on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='finance.fund', verbose_name='Fund')),
                ('organization', models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-date', '-voucher_no'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('description', models.CharField(help_text='Description of this journal entry line.', max_length=255, verbose_name='Description')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Debit amount (leave 0 for credit entries).', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Debit')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit amount (leave 0 for debit entries).', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Credit')),
                ('budget_head', models.ForeignKey(help_text='GL account to post to.', on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='finance.budgethead', verbose_name='Budget Head')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.voucher', verbose_name='Voucher')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['voucher', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['organization', 'fiscal_year'], name='finance_vou_organiz_7fe86f_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['date'], name='finance_vou_date_e3cc9b_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['is_posted'], name='finance_vou_is_post_c0eb7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together={('organization', 'fiscal_year', 'voucher_no')},
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['voucher'], name='finance_jou_voucher_65472e_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['budget_head'], name='finance_jou_budget__de434d_idx'),
        ),
    ]
