# Generated by Django 4.2.25 on 2026-01-26 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_fund_voucher_journalentry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgethead',
            options={'ordering': ['fund', 'pifra_object', 'tma_sub_object'], 'verbose_name': 'Budget Head', 'verbose_name_plural': 'Budget Heads'},
        ),
        migrations.RemoveField(
            model_name='budgethead',
            name='fund_id',
        ),
        migrations.AddField(
            model_name='budgethead',
            name='fund',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='budget_heads', to='finance.fund', verbose_name='Fund'),
        ),
    ]
