# Generated by Django 4.2.25 on 2026-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_budgethead_options_remove_budgethead_fund_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgethead',
            name='is_system_head',
            field=models.BooleanField(default=False, help_text='Whether this is a system-controlled head for automated GL posting.', verbose_name='Is System Head'),
        ),
        migrations.AddField(
            model_name='budgethead',
            name='system_code',
            field=models.CharField(blank=True, choices=[('AP', 'Accounts Payable'), ('TAX_IT', 'Income Tax'), ('TAX_GST', 'GST/Sales Tax'), ('AR', 'Accounts Receivable')], help_text='Unique code for system-controlled heads (AP, TAX_IT, TAX_GST, AR).', max_length=10, null=True, unique=True, verbose_name='System Code'),
        ),
    ]
