# Generated by Django 6.0.1 on 2026-01-27 19:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_organization_bank_account_no_and_more'),
        ('finance', '0006_budgethead_is_system_head_budgethead_system_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active in the system.', verbose_name='Is Active')),
                ('book_no', models.CharField(help_text='Unique cheque book identifier (e.g., BK-2025-01).', max_length=50, verbose_name='Book Number')),
                ('prefix', models.CharField(blank=True, default='', help_text='Prefix for leaf numbers (e.g., "00", "CHQ").', max_length=10, verbose_name='Prefix')),
                ('start_serial', models.PositiveIntegerField(help_text='Starting serial number (e.g., 1001).', verbose_name='Start Serial')),
                ('end_serial', models.PositiveIntegerField(help_text='Ending serial number (e.g., 1050).', verbose_name='End Serial')),
                ('issue_date', models.DateField(help_text='Date the book was received from bank.', verbose_name='Issue Date')),
                ('bank_account', models.ForeignKey(help_text='Bank account this cheque book belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='cheque_books', to='core.bankaccount', verbose_name='Bank Account')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Cheque Book',
                'verbose_name_plural': 'Cheque Books',
                'ordering': ['-issue_date', 'book_no'],
            },
        ),
        migrations.CreateModel(
            name='ChequeLeaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('leaf_number', models.CharField(help_text='Full composite cheque number (e.g., A1001).', max_length=30, verbose_name='Leaf Number')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=15, verbose_name='Status')),
                ('void_reason', models.TextField(blank=True, help_text='Reason for cancellation or damage.', verbose_name='Void Reason')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the leaf was issued/used.', null=True, verbose_name='Used At')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='finance.chequebook', verbose_name='Cheque Book')),
            ],
            options={
                'verbose_name': 'Cheque Leaf',
                'verbose_name_plural': 'Cheque Leaves',
                'ordering': ['book', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='chequebook',
            index=models.Index(fields=['bank_account', 'is_active'], name='finance_che_bank_ac_487ced_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chequebook',
            unique_together={('bank_account', 'book_no')},
        ),
        migrations.AddIndex(
            model_name='chequeleaf',
            index=models.Index(fields=['book', 'status'], name='finance_che_book_id_49064c_idx'),
        ),
        migrations.AddIndex(
            model_name='chequeleaf',
            index=models.Index(fields=['leaf_number'], name='finance_che_leaf_nu_fe1c4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='chequeleaf',
            constraint=models.UniqueConstraint(fields=('book', 'leaf_number'), name='unique_leaf_per_book'),
        ),
    ]
