# Generated by Django 6.0.1 on 2026-01-28 04:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0012_phase3_pension_budget_execution'),
        ('core', '0005_remove_organization_bank_account_no_and_more'),
        ('finance', '0007_chequebook_chequeleaf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('month', models.PositiveSmallIntegerField(help_text='Statement month (1-12).', verbose_name='Month')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance at the start of the statement period.', max_digits=15, verbose_name='Opening Balance')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance at the end of the statement period.', max_digits=15, verbose_name='Closing Balance')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RECONCILING', 'Reconciling'), ('RECONCILED', 'Reconciled'), ('LOCKED', 'Locked')], default='DRAFT', max_length=15, verbose_name='Status')),
                ('is_locked', models.BooleanField(default=False, help_text='Whether this statement is locked after reconciliation.', verbose_name='Is Locked')),
                ('file', models.FileField(blank=True, help_text='Uploaded bank statement file (CSV or PDF).', null=True, upload_to='bank_statements/%Y/%m/', verbose_name='Statement File')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this statement.', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Bank Statement',
                'verbose_name_plural': 'Bank Statements',
                'ordering': ['-year__start_date', '-month'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('date', models.DateField(help_text='Date of the transaction as per bank.', verbose_name='Transaction Date')),
                ('description', models.CharField(help_text='Transaction description from bank statement.', max_length=255, verbose_name='Description')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount debited/withdrawn from account.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Debit (Withdrawal)')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount credited/deposited to account.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Credit (Deposit)')),
                ('ref_no', models.CharField(blank=True, db_index=True, help_text='Cheque number or transaction reference from bank.', max_length=50, verbose_name='Reference No')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running balance after this transaction.', max_digits=15, verbose_name='Balance')),
                ('is_reconciled', models.BooleanField(default=False, help_text='Whether this line has been matched with GL entry.', verbose_name='Is Reconciled')),
            ],
            options={
                'verbose_name': 'Bank Statement Line',
                'verbose_name_plural': 'Bank Statement Lines',
                'ordering': ['statement', 'date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='instrument_no',
            field=models.CharField(blank=True, db_index=True, help_text='Cheque number or transaction reference for bank reconciliation.', max_length=50, verbose_name='Instrument No'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_reconciled',
            field=models.BooleanField(default=False, help_text='Whether this entry has been reconciled with bank statement.', verbose_name='Is Reconciled'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reconciled_date',
            field=models.DateField(blank=True, help_text='Date when this entry was reconciled.', null=True, verbose_name='Reconciled Date'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['is_reconciled'], name='finance_jou_is_reco_a607e4_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['instrument_no'], name='finance_jou_instrum_a7c970_idx'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='bank_account',
            field=models.ForeignKey(help_text='Bank account this statement belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='core.bankaccount', verbose_name='Bank Account'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='year',
            field=models.ForeignKey(help_text='Fiscal year this statement belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='bank_statements', to='budgeting.fiscalyear', verbose_name='Fiscal Year'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='matched_entry',
            field=models.OneToOneField(blank=True, help_text='The GL journal entry this line is matched to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_match', to='finance.journalentry', verbose_name='Matched Entry'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.bankstatement', verbose_name='Statement'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['bank_account', 'year', 'month'], name='finance_ban_bank_ac_c45a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['status'], name='finance_ban_status_0d9cc2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankstatement',
            unique_together={('bank_account', 'month', 'year')},
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['statement', 'is_reconciled'], name='finance_ban_stateme_80d1a1_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['ref_no'], name='finance_ban_ref_no_713f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['date'], name='finance_ban_date_84f2de_idx'),
        ),
    ]
