# Generated by Django 4.2.25 on 2026-01-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_bankstatement_bankstatementline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='payee',
            field=models.CharField(blank=True, help_text='Name of payee or party (optional).', max_length=200, verbose_name='Payee'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reference_no',
            field=models.CharField(blank=True, help_text='External reference number (optional).', max_length=50, verbose_name='Reference No'),
        ),
    ]
