# Generated by Django 4.2.25 on 2026-01-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_voucher_payee_voucher_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgethead',
            name='major_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Major Description'),
        ),
        migrations.AddField(
            model_name='budgethead',
            name='major_object',
            field=models.CharField(blank=True, help_text='PIFRA Major Object (e.g., A01).', max_length=10, verbose_name='Major Object Code'),
        ),
        migrations.AddField(
            model_name='budgethead',
            name='minor_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Minor Description'),
        ),
        migrations.AddField(
            model_name='budgethead',
            name='minor_object',
            field=models.CharField(blank=True, help_text='PIFRA Minor Object (e.g., A011).', max_length=10, verbose_name='Minor Object Code'),
        ),
    ]
