# Generated by Django 6.0.1 on 2026-01-29 16:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_budgethead_major_description_budgethead_major_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('code', models.CharField(help_text='Detailed object code (e.g., A01101).', max_length=20, unique=True, verbose_name='Object Code')),
                ('name', models.CharField(max_length=255, verbose_name='Object Name')),
                ('account_type', models.CharField(choices=[('EXP', 'Expenditure'), ('REV', 'Revenue'), ('LIA', 'Liability'), ('AST', 'Asset'), ('EQT', 'Equity')], default='EXP', max_length=3, verbose_name='Account Type')),
                ('system_code', models.CharField(blank=True, choices=[('SYS_SUSPENSE', 'Suspense Account'), ('CLEARING_CHQ', 'Cheque Clearing'), ('CLEARING_IT', 'Income Tax Withheld'), ('CLEARING_GST', 'Sales Tax Withheld'), ('CLEARING_SEC', 'Security/Retention Money')], help_text='System code for automated workflows (Suspense, Clearing, etc.).', max_length=20, null=True, unique=True, verbose_name='System Code')),
            ],
            options={
                'verbose_name': 'Global Head',
                'verbose_name_plural': 'Global Heads',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MajorHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('code', models.CharField(help_text='Major object code (e.g., A01, A03, C01).', max_length=10, unique=True, verbose_name='Major Code')),
                ('name', models.CharField(help_text='Description of major object (e.g., Employee Related Expenses).', max_length=255, verbose_name='Major Name')),
            ],
            options={
                'verbose_name': 'Major Head',
                'verbose_name_plural': 'Major Heads',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MinorHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('code', models.CharField(help_text='Minor object code (e.g., A011, A012).', max_length=10, unique=True, verbose_name='Minor Code')),
                ('name', models.CharField(max_length=255, verbose_name='Minor Name')),
            ],
            options={
                'verbose_name': 'Minor Head',
                'verbose_name_plural': 'Minor Heads',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='budgethead',
            options={'ordering': ['fund', 'global_head__code'], 'verbose_name': 'Budget Head', 'verbose_name_plural': 'Budget Heads'},
        ),
        migrations.RemoveIndex(
            model_name='budgethead',
            name='finance_bud_pifra_o_7c2fcb_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgethead',
            name='finance_bud_tma_sub_cda0aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgethead',
            name='finance_bud_fund_ty_e2a06d_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgethead',
            name='finance_bud_account_13a1b8_idx',
        ),
        migrations.AddField(
            model_name='budgethead',
            name='current_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current budget allocation for this head.', max_digits=15, verbose_name='Current Budget'),
        ),
        migrations.AlterField(
            model_name='budgethead',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_heads', to='finance.fund', verbose_name='Fund'),
        ),
        migrations.AddField(
            model_name='budgethead',
            name='global_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_heads', to='finance.globalhead', verbose_name='Global Head'),
        ),
        migrations.AlterUniqueTogether(
            name='budgethead',
            unique_together={('fund', 'global_head')},
        ),
        migrations.AddIndex(
            model_name='budgethead',
            index=models.Index(fields=['fund', 'global_head'], name='finance_bud_fund_id_258131_idx'),
        ),
        migrations.AddIndex(
            model_name='budgethead',
            index=models.Index(fields=['is_active'], name='finance_bud_is_acti_d2d8dc_idx'),
        ),
        migrations.AddField(
            model_name='minorhead',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minor_heads', to='finance.majorhead', verbose_name='Major Head'),
        ),
        migrations.AddField(
            model_name='globalhead',
            name='minor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='global_heads', to='finance.minorhead', verbose_name='Minor Head'),
        ),
        migrations.RemoveField(
            model_name='budgethead',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='budgethead',
            name='fund_type',
        ),
        migrations.RemoveField(
            model_name='budgethead',
            name='is_charged',
        ),
        migrations.RemoveField(
            model_name='budgethead',
            name='is_system_head',
        ),
        migrations.RemoveField(
            model_name='budgethead',
            name='major_description',
        ),
        migrations.RemoveField(
            model_name='budgethead',
            name='major_object',
        ),
        migrations.RemoveField(
            model_name='budgethead',
            name='minor_description',
        ),
        migrations.RemoveField(
            model_name='budgethead',
            name='minor_object',
        ),
        migrations.RemoveField(
            model_name='budgethead',
            name='pifra_description',
        ),
        migrations.RemoveField(
            model_name='budgethead',
            name='pifra_object',
        ),
        migrations.RemoveField(
            model_name='budgethead',
            name='system_code',
        ),
        migrations.RemoveField(
            model_name='budgethead',
            name='tma_description',
        ),
        migrations.RemoveField(
            model_name='budgethead',
            name='tma_sub_object',
        ),
        migrations.AddIndex(
            model_name='globalhead',
            index=models.Index(fields=['code'], name='finance_glo_code_ca27bc_idx'),
        ),
        migrations.AddIndex(
            model_name='globalhead',
            index=models.Index(fields=['account_type'], name='finance_glo_account_337a3d_idx'),
        ),
    ]
