# Generated by Django 6.0.1 on 2026-01-29 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_globalhead_majorhead_minorhead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgethead',
            name='global_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_heads', to='finance.globalhead', verbose_name='Global Head'),
        ),
    ]
