# Generated by Django 4.2.25 on 2026-01-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_budgethead_global_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalhead',
            name='system_code',
            field=models.CharField(blank=True, choices=[('SYS_SUSPENSE', 'Suspense Account'), ('CLEARING_CHQ', 'Cheque Clearing'), ('CLEARING_IT', 'Income Tax Withheld'), ('CLEARING_GST', 'Sales Tax Withheld'), ('CLEARING_SEC', 'Security/Retention Money'), ('AR', 'Accounts Receivable')], help_text='System code for automated workflows (Suspense, Clearing, etc.).', max_length=20, null=True, unique=True, verbose_name='System Code'),
        ),
    ]
