# Generated by Django 4.2.25 on 2026-01-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_globalhead_system_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgethead',
            unique_together={('fund', 'global_head', 'function')},
        ),
    ]
