# Generated by Django 6.0.1 on 2026-01-30 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_budgethead_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgethead',
            options={'ordering': ['fund', 'function__code', 'global_head__code', 'sub_code'], 'verbose_name': 'Budget Head', 'verbose_name_plural': 'Budget Heads'},
        ),
        migrations.AlterUniqueTogether(
            name='budgethead',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budgethead',
            name='head_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Head'), ('SUB_HEAD', 'Local Sub-Head')], default='REGULAR', help_text='REGULAR for standard objects, SUB_HEAD for local breakdowns.', max_length=10, verbose_name='Head Type'),
        ),
        migrations.AddField(
            model_name='budgethead',
            name='local_description',
            field=models.CharField(blank=True, default='', help_text='Custom name for sub-heads (e.g., "Rent of Shops", "Annual Sports Festival").', max_length=255, verbose_name='Local Description'),
        ),
        migrations.AddField(
            model_name='budgethead',
            name='sub_code',
            field=models.CharField(default='00', help_text="'00' for regular heads, '01'-'99' for local sub-divisions.", max_length=5, verbose_name='Sub-Code'),
        ),
        migrations.AlterField(
            model_name='budgethead',
            name='function',
            field=models.ForeignKey(default=1, help_text='Functional classification (e.g., AD for Admin, WS for Water Supply).', on_delete=django.db.models.deletion.PROTECT, related_name='budget_heads', to='finance.functioncode', verbose_name='Function'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgethead',
            name='global_head',
            field=models.ForeignKey(help_text='PIFRA Object code from master chart.', on_delete=django.db.models.deletion.PROTECT, related_name='budget_heads', to='finance.globalhead', verbose_name='Global Head'),
        ),
        migrations.AlterUniqueTogether(
            name='budgethead',
            unique_together={('fund', 'function', 'global_head', 'sub_code')},
        ),
        migrations.AddIndex(
            model_name='budgethead',
            index=models.Index(fields=['function'], name='finance_bud_functio_ae08c4_idx'),
        ),
    ]
