# Generated by Django 4.2.25 on 2026-02-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_budgethead_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalhead',
            name='system_code',
            field=models.CharField(blank=True, choices=[('SYS_SUSPENSE', 'Suspense Account'), ('CLEARING_CHQ', 'Cheque Clearing'), ('CLEARING_IT', 'Income Tax Withheld'), ('CLEARING_GST', 'Sales Tax Withheld'), ('CLEARING_SEC', 'Security/Retention Money'), ('AP', 'Accounts Payable'), ('AR', 'Accounts Receivable'), ('TAX_IT', 'Income Tax Payable'), ('TAX_GST', 'GST/Sales Tax Payable')], help_text='System code for automated workflows (Suspense, Clearing, etc.).', max_length=20, null=True, unique=True, verbose_name='System Code'),
        ),
    ]
