# Generated by Django 4.2.25 on 2026-02-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0021_budgetemployee_expected_salary_increase_percentage'),
        ('finance', '0016_alter_globalhead_system_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalhead',
            name='applicable_departments',
            field=models.ManyToManyField(blank=True, help_text='Select departments where this head is relevant. Leave empty for Universal scope.', related_name='applicable_global_heads', to='budgeting.department', verbose_name='Applicable Departments'),
        ),
        migrations.AddField(
            model_name='globalhead',
            name='scope',
            field=models.CharField(choices=[('UNIVERSAL', 'Universal - All Departments'), ('DEPARTMENTAL', 'Department-Specific')], default='UNIVERSAL', help_text='Universal heads appear for all departments. Departmental heads only for selected departments.', max_length=20, verbose_name='Scope'),
        ),
    ]
