# Generated by Django 4.2.25 on 2026-02-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_add_reporting_indexes'),
        ('finance', '0018_add_usage_notes_to_functioncode'),
    ]

    operations = [
    ]
