# Generated by Django 4.2.25 on 2026-02-04 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0019_merge_20260204_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50, verbose_name='Voucher Number')),
                ('action', models.CharField(choices=[('POST', 'Posted to GL'), ('UNPOST', 'Unposted from GL'), ('EDIT', 'Edited'), ('DELETE', 'Deleted')], max_length=10, verbose_name='Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('reason', models.TextField(blank=True, verbose_name='Reason/Notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
            ],
            options={
                'verbose_name': 'Voucher Audit Log',
                'verbose_name_plural': 'Voucher Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='je_budget_voucher_idx',
        ),
        migrations.RemoveIndex(
            model_name='voucher',
            name='voucher_date_posted_idx',
        ),
        migrations.RemoveIndex(
            model_name='voucher',
            name='voucher_no_idx',
        ),
        migrations.AddField(
            model_name='voucherauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='voucherauditlog',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='finance.voucher', verbose_name='Voucher'),
        ),
        migrations.AddIndex(
            model_name='voucherauditlog',
            index=models.Index(fields=['voucher', '-timestamp'], name='finance_vou_voucher_fc6f44_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherauditlog',
            index=models.Index(fields=['voucher_no'], name='finance_vou_voucher_7e4aa1_idx'),
        ),
    ]
