# Generated by Django 4.2.25 on 2026-02-05 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0020_voucherauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='is_reversed',
            field=models.BooleanField(default=False, help_text='True if this voucher has been reversed.', verbose_name='Is Reversed'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reversal_reason',
            field=models.TextField(blank=True, help_text='Reason for reversal (required when reversing).', verbose_name='Reversal Reason'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reversed At'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Reversed By'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reversed_by_voucher',
            field=models.OneToOneField(blank=True, help_text='If this voucher was reversed, link to the reversal voucher.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_voucher', to='finance.voucher', verbose_name='Reversed By Voucher'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reverses_voucher',
            field=models.ForeignKey(blank=True, help_text='If this is a reversal voucher, link to the original voucher.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_vouchers', to='finance.voucher', verbose_name='Reverses Voucher'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('JV', 'Journal Voucher'), ('PV', 'Payment Voucher'), ('RV', 'Receipt Voucher'), ('REV', 'Reversal Voucher')], default='JV', max_length=3, verbose_name='Voucher Type'),
        ),
    ]
