# Generated by Django 6.0.1 on 2026-02-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_add_reversal_voucher_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalhead',
            name='applicable_functions',
            field=models.ManyToManyField(blank=True, help_text='Leave empty for universal heads (appear for all functions). Select specific functions to restrict this head.', related_name='applicable_global_heads', to='finance.functioncode', verbose_name='Applicable Functions'),
        ),
    ]
