# Generated by Django 6.0.1 on 2026-02-07 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0027_budgetemployee_organization'),
        ('core', '0006_notification'),
        ('finance', '0023_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='budgethead',
            name='finance_bh_fund_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgethead',
            name='finance_bh_posting_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='finance_je_bh_reconciled_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='finance_je_voucher_bh_idx',
        ),
        migrations.RemoveIndex(
            model_name='voucher',
            name='finance_v_reversed_idx',
        ),
        migrations.RenameIndex(
            model_name='voucher',
            new_name='finance_vou_organiz_df9679_idx',
            old_name='finance_v_org_date_posted_idx',
        ),
        migrations.AlterField(
            model_name='globalhead',
            name='system_code',
            field=models.CharField(blank=True, choices=[('SYS_SUSPENSE', 'Suspense Account'), ('CLEARING_CHQ', 'Cheque Clearing'), ('CLEARING_IT', 'Income Tax Withheld'), ('CLEARING_GST', 'Sales Tax Withheld'), ('CLEARING_SEC', 'Security/Retention Money'), ('AP', 'Accounts Payable'), ('AR', 'Accounts Receivable'), ('TAX_IT', 'Income Tax Payable'), ('TAX_GST', 'GST/Sales Tax Payable'), ('TAX_STAMP', 'Stamp Duty Payable')], help_text='System code for automated workflows (Suspense, Clearing, etc.).', max_length=20, null=True, unique=True, verbose_name='System Code'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['is_reversed'], name='finance_vou_is_reve_648552_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['fiscal_year', 'voucher_type', 'is_posted'], name='finance_vou_fiscal__72e833_idx'),
        ),
    ]
