# Generated by Django 6.0.1 on 2026-02-07 10:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0027_budgetemployee_organization'),
        ('core', '0006_notification'),
        ('finance', '0024_remove_budgethead_finance_bh_fund_active_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Month number (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(12)], verbose_name='Month')),
                ('opening_balance_dr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Opening Balance (Debit)')),
                ('opening_balance_cr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Opening Balance (Credit)')),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Debit')),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Credit')),
                ('closing_balance_dr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Closing Balance (Debit)')),
                ('closing_balance_cr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Closing Balance (Credit)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Account Balance',
                'verbose_name_plural': 'Account Balances',
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['voucher', 'budget_head'], name='finance_jou_voucher_a38bac_idx'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='budget_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_balances', to='finance.budgethead', verbose_name='Budget Head'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_balances', to='budgeting.fiscalyear', verbose_name='Fiscal Year'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization'),
        ),
        migrations.AddIndex(
            model_name='accountbalance',
            index=models.Index(fields=['organization', 'fiscal_year', 'month'], name='finance_acc_organiz_2f8460_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalance',
            index=models.Index(fields=['fiscal_year', 'budget_head'], name='finance_acc_fiscal__fa21dc_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalance',
            index=models.Index(fields=['organization', 'fiscal_year', 'budget_head'], name='finance_acc_organiz_e0ce2a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountbalance',
            unique_together={('organization', 'fiscal_year', 'budget_head', 'month')},
        ),
    ]
