# Generated by Django 4.2.25 on 2026-02-08 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0027_budgetemployee_organization'),
        ('finance', '0025_accountbalance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgethead',
            options={'ordering': ['department__name', 'function__code', 'global_head__code', 'sub_code'], 'verbose_name': 'Budget Head', 'verbose_name_plural': 'Budget Heads'},
        ),
        migrations.AlterUniqueTogether(
            name='budgethead',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budgethead',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department responsible for this budget head.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_heads', to='budgeting.department', verbose_name='Department'),
        ),
        migrations.AlterUniqueTogether(
            name='budgethead',
            unique_together={('department', 'fund', 'function', 'global_head', 'sub_code')},
        ),
        migrations.AddIndex(
            model_name='budgethead',
            index=models.Index(fields=['department', 'function', 'is_active'], name='finance_bud_departm_bd46b3_idx'),
        ),
        migrations.AddIndex(
            model_name='budgethead',
            index=models.Index(fields=['department', 'is_active'], name='finance_bud_departm_f35b72_idx'),
        ),
    ]
