# Generated by Django 4.2.25 on 2026-02-08 12:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0027_budgetemployee_organization'),
        ('finance', '0026_add_department_to_budgethead'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentFunctionConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_locked', models.BooleanField(default=False, help_text='Lock this configuration to prevent changes during fiscal year.', verbose_name='Is Locked')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this configuration.', verbose_name='Configuration Notes')),
                ('allowed_global_heads', models.ManyToManyField(blank=True, help_text='Global heads that can be used for this department-function combination.', related_name='dept_func_configurations', to='finance.globalhead', verbose_name='Allowed Global Heads')),
                ('department', models.ForeignKey(help_text='Department for this configuration.', on_delete=django.db.models.deletion.PROTECT, related_name='function_configurations', to='budgeting.department', verbose_name='Department')),
                ('function', models.ForeignKey(help_text='Functional classification for this configuration.', on_delete=django.db.models.deletion.PROTECT, related_name='department_configurations', to='finance.functioncode', verbose_name='Function')),
            ],
            options={
                'verbose_name': 'Department-Function Configuration',
                'verbose_name_plural': 'Department-Function Configurations',
                'ordering': ['department__name', 'function__code'],
                'indexes': [models.Index(fields=['department', 'function'], name='finance_dep_departm_358ac0_idx'), models.Index(fields=['is_locked'], name='finance_dep_is_lock_123613_idx')],
                'unique_together': {('department', 'function')},
            },
        ),
    ]
