# Generated by Django 4.2.25 on 2026-02-08 12:27

from django.db import migrations


def populate_configurations_from_budget_heads(apps, schema_editor):
    """
    Populate DepartmentFunctionConfiguration from existing BudgetHead data.
    
    Logic:
    1. Find all distinct Department-Function combinations from BudgetHead
    2. For each combination, create a DepartmentFunctionConfiguration
    3. Collect all GlobalHeads used for that combination
    4. Add those GlobalHeads to the allowed_global_heads
    """
    BudgetHead = apps.get_model('finance', 'BudgetHead')
    DepartmentFunctionConfiguration = apps.get_model('finance', 'DepartmentFunctionConfiguration')
    
    # Get distinct department-function pairs from existing budget heads
    dept_func_pairs = BudgetHead.objects.filter(
        department__isnull=False,
        function__isnull=False,
        is_active=True
    ).values('department', 'function').distinct()
    
    created_count = 0
    for pair in dept_func_pairs:
        dept_id = pair['department']
        func_id = pair['function']
        
        # Create configuration (or get if exists)
        config, created = DepartmentFunctionConfiguration.objects.get_or_create(
            department_id=dept_id,
            function_id=func_id,
            defaults={'is_locked': False, 'notes': 'Auto-generated from existing BudgetHeads'}
        )
        
        if created:
            created_count += 1
        
        # Get all global heads used for this dept-func combination
        global_head_ids = BudgetHead.objects.filter(
            department_id=dept_id,
            function_id=func_id,
            is_active=True
        ).values_list('global_head_id', flat=True).distinct()
        
        # Add to allowed_global_heads
        config.allowed_global_heads.set(global_head_ids)
    
    print(f"Created {created_count} Department-Function configurations from existing BudgetHeads")


def reverse_migration(apps, schema_editor):
    """Remove all auto-generated configurations."""
    DepartmentFunctionConfiguration = apps.get_model('finance', 'DepartmentFunctionConfiguration')
    DepartmentFunctionConfiguration.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_add_dept_func_configuration'),
    ]

    operations = [
        migrations.RunPython(populate_configurations_from_budget_heads, reverse_migration),
    ]
