# Generated by Django 4.2.25 on 2026-02-08 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0028_populate_dept_func_configurations'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetHeadUsageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('last_used', models.DateTimeField(auto_now=True, help_text='Timestamp of last use.', verbose_name='Last Used')),
                ('usage_count', models.PositiveIntegerField(default=1, help_text='Number of times this head has been used.', verbose_name='Usage Count')),
                ('budget_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='finance.budgethead', verbose_name='Budget Head')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_head_usage_history', to='core.organization', verbose_name='Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_head_usage_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Budget Head Usage History',
                'verbose_name_plural': 'Budget Head Usage History',
                'ordering': ['-last_used'],
                'indexes': [models.Index(fields=['user', 'organization', '-last_used'], name='finance_bud_user_id_8c2f62_idx')],
                'unique_together': {('user', 'budget_head', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='BudgetHeadFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('budget_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='finance.budgethead', verbose_name='Budget Head')),
                ('organization', models.ForeignKey(help_text='Organization context for this favorite.', on_delete=django.db.models.deletion.CASCADE, related_name='budget_head_favorites', to='core.organization', verbose_name='Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_head_favorites', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Budget Head Favorite',
                'verbose_name_plural': 'Budget Head Favorites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'organization'], name='finance_bud_user_id_c02102_idx')],
                'unique_together': {('user', 'budget_head', 'organization')},
            },
        ),
    ]
