# Generated by Django 6.0.1 on 2026-02-08 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0027_budgetemployee_organization'),
        ('finance', '0029_add_budget_head_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budgethead',
            index=models.Index(fields=['department', 'function', 'is_active', 'posting_allowed'], name='budgethead_search_idx'),
        ),
        migrations.AddIndex(
            model_name='budgethead',
            index=models.Index(fields=['global_head', 'is_active'], name='budgethead_globalhead_idx'),
        ),
    ]
