# Generated by Django 4.2.25 on 2026-02-09 05:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0028_alter_budgetallocation_options'),
        ('finance', '0030_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAMHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('code', models.CharField(help_text='Format: A12001, A01101', max_length=10, unique=True, verbose_name='NAM Code')),
                ('name', models.CharField(max_length=255, verbose_name='NAM Name')),
                ('account_type', models.CharField(choices=[('EXP', 'Expenditure'), ('REV', 'Revenue'), ('LIA', 'Liability'), ('AST', 'Asset'), ('EQT', 'Equity')], default='EXP', max_length=3, verbose_name='Account Type')),
                ('scope', models.CharField(choices=[('UNIVERSAL', 'Universal - All Departments'), ('RESTRICTED', 'Restricted to Selected Departments')], default='UNIVERSAL', max_length=20, verbose_name='Scope')),
                ('allow_direct_posting', models.BooleanField(default=True, help_text='Allow posting when no sub-heads exist. Auto-set to False when sub-heads are created.', verbose_name='Allow Direct Posting')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'NAM Head',
                'verbose_name_plural': 'NAM Heads',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('sub_code', models.CharField(help_text='Format: 01, 02, 03, etc.', max_length=2, verbose_name='Sub Code')),
                ('name', models.CharField(help_text='Descriptive name for this sub-head', max_length=255, verbose_name='Sub-Head Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sub-Head',
                'verbose_name_plural': 'Sub-Heads',
                'ordering': ['nam_head', 'sub_code'],
            },
        ),
        migrations.AlterModelOptions(
            name='budgethead',
            options={'ordering': ['department__name', 'function__code', 'nam_head__code', 'sub_head__sub_code'], 'verbose_name': 'Budget Head', 'verbose_name_plural': 'Budget Heads'},
        ),
        migrations.RemoveIndex(
            model_name='budgethead',
            name='finance_bud_fund_id_258131_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgethead',
            name='budgethead_globalhead_idx',
        ),
        # Note: Indexes for nam_head/sub_head moved to after AddField operations
        migrations.AddField(
            model_name='subhead',
            name='nam_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_heads', to='finance.namhead', verbose_name='Parent NAM Head'),
        ),
        migrations.AddField(
            model_name='namhead',
            name='applicable_departments',
            field=models.ManyToManyField(blank=True, related_name='applicable_nam_heads', to='budgeting.department', verbose_name='Applicable Departments'),
        ),
        migrations.AddField(
            model_name='namhead',
            name='applicable_functions',
            field=models.ManyToManyField(blank=True, related_name='applicable_nam_heads', to='finance.functioncode', verbose_name='Applicable Functions'),
        ),
        migrations.AddField(
            model_name='namhead',
            name='minor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nam_heads', to='finance.minorhead', verbose_name='Minor Head'),
        ),
        migrations.AlterUniqueTogether(
            name='budgethead',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budgethead',
            name='nam_head',
            field=models.ForeignKey(blank=True, help_text='Level 4: Use when no sub-heads exist', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_heads', to='finance.namhead', verbose_name='NAM Head'),
        ),
        migrations.AddField(
            model_name='budgethead',
            name='sub_head',
            field=models.ForeignKey(blank=True, help_text='Level 5: Use for sub-head breakdown', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_heads', to='finance.subhead', verbose_name='Sub-Head'),
        ),
        # NOW add the indexes on budgethead after fields are created
        migrations.AddIndex(
            model_name='budgethead',
            index=models.Index(fields=['fund', 'nam_head'], name='finance_bud_fund_id_2fac0a_idx'),
        ),
        migrations.AddIndex(
            model_name='budgethead',
            index=models.Index(fields=['fund', 'sub_head'], name='finance_bud_fund_id_396faf_idx'),
        ),
        migrations.AddIndex(
            model_name='budgethead',
            index=models.Index(fields=['nam_head', 'is_active'], name='finance_bud_nam_hea_9c8cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='budgethead',
            index=models.Index(fields=['sub_head', 'is_active'], name='finance_bud_sub_hea_c7465d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgethead',
            unique_together={('department', 'fund', 'function', 'nam_head', 'sub_head')},
        ),
        migrations.AddIndex(
            model_name='subhead',
            index=models.Index(fields=['nam_head', 'is_active'], name='finance_sub_nam_hea_7308de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subhead',
            unique_together={('nam_head', 'sub_code')},
        ),
        migrations.AddIndex(
            model_name='namhead',
            index=models.Index(fields=['code'], name='finance_nam_code_00add2_idx'),
        ),
        migrations.AddIndex(
            model_name='namhead',
            index=models.Index(fields=['account_type'], name='finance_nam_account_7e6fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='namhead',
            index=models.Index(fields=['is_active'], name='finance_nam_is_acti_53f0e7_idx'),
        ),
        migrations.RemoveField(
            model_name='budgethead',
            name='global_head',
        ),
        migrations.RemoveField(
            model_name='budgethead',
            name='head_type',
        ),
        migrations.RemoveField(
            model_name='budgethead',
            name='local_description',
        ),
        migrations.RemoveField(
            model_name='budgethead',
            name='sub_code',
        ),
    ]
