# Generated by Django 4.2.25 on 2026-02-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_namhead_subhead_alter_budgethead_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentfunctionconfiguration',
            name='allowed_nam_heads',
            field=models.ManyToManyField(blank=True, help_text='NAM heads that can be used for this department-function combination.', related_name='dept_func_configurations', to='finance.namhead', verbose_name='Allowed NAM Heads'),
        ),
        migrations.AlterField(
            model_name='departmentfunctionconfiguration',
            name='allowed_global_heads',
            field=models.ManyToManyField(blank=True, help_text='Legacy field - use allowed_nam_heads instead.', related_name='dept_func_configurations_legacy', to='finance.namhead', verbose_name='Allowed Global Heads (Legacy)'),
        ),
    ]
