# Generated by Django 4.2.25 on 2026-02-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0028_alter_budgetallocation_options'),
        ('finance', '0032_departmentfunctionconfiguration_allowed_nam_heads_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentfunctionconfiguration',
            name='allowed_global_heads',
        ),
        migrations.AlterField(
            model_name='departmentfunctionconfiguration',
            name='allowed_nam_heads',
            field=models.ManyToManyField(blank=True, help_text='NAM heads that can be used for this department-function combination. This is the ONLY access control mechanism - scope fields are deprecated.', related_name='dept_func_configurations', to='finance.namhead', verbose_name='Allowed NAM Heads'),
        ),
        migrations.AlterField(
            model_name='globalhead',
            name='applicable_departments',
            field=models.ManyToManyField(blank=True, help_text='DEPRECATED: Use DepartmentFunctionConfiguration instead.', related_name='applicable_global_heads', to='budgeting.department', verbose_name='Applicable Departments (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='globalhead',
            name='applicable_functions',
            field=models.ManyToManyField(blank=True, help_text='DEPRECATED: Use DepartmentFunctionConfiguration instead.', related_name='applicable_global_heads', to='finance.functioncode', verbose_name='Applicable Functions (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='globalhead',
            name='scope',
            field=models.CharField(choices=[('UNIVERSAL', 'Universal - All Departments'), ('DEPARTMENTAL', 'Department-Specific')], default='UNIVERSAL', help_text='DEPRECATED: Use DepartmentFunctionConfiguration instead.', max_length=20, verbose_name='Scope (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='namhead',
            name='applicable_departments',
            field=models.ManyToManyField(blank=True, help_text='DEPRECATED: Configure via DepartmentFunctionConfiguration instead.', related_name='applicable_nam_heads', to='budgeting.department', verbose_name='Applicable Departments (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='namhead',
            name='applicable_functions',
            field=models.ManyToManyField(blank=True, help_text='DEPRECATED: Configure via DepartmentFunctionConfiguration instead.', related_name='applicable_nam_heads', to='finance.functioncode', verbose_name='Applicable Functions (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='namhead',
            name='scope',
            field=models.CharField(choices=[('UNIVERSAL', 'Universal - All Departments'), ('RESTRICTED', 'Restricted to Selected Departments')], default='UNIVERSAL', help_text='DEPRECATED: Use DepartmentFunctionConfiguration for access control.', max_length=20, verbose_name='Scope (DEPRECATED)'),
        ),
    ]
