# Generated by Django 6.0.1 on 2026-01-24 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Division Name')),
                ('code', models.CharField(blank=True, help_text='Short code for the division.', max_length=10, unique=True, verbose_name='Division Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='District Name')),
                ('code', models.CharField(blank=True, help_text='Short code for the district.', max_length=10, verbose_name='District Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='core.division', verbose_name='Division')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['division__name', 'name'],
                'unique_together': {('division', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Tehsil/TMA Name')),
                ('code', models.CharField(blank=True, help_text='Unique code for the TMA (auto-generated if blank).', max_length=20, unique=True, verbose_name='TMA Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tmas', to='core.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'TMA',
                'verbose_name_plural': 'TMAs',
                'ordering': ['district__division__name', 'district__name', 'name'],
                'unique_together': {('district', 'name')},
            },
        ),
    ]
