# Generated by Django 6.0.1 on 2026-01-24 19:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_district_public_id_division_public_id_tma_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID'),
        ),
        migrations.AlterField(
            model_name='division',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID'),
        ),
        migrations.AlterField(
            model_name='tma',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID'),
        ),
    ]
