# Generated by Django 6.0.1 on 2026-01-25 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_district_public_id_alter_division_public_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tehsil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Tehsil Name')),
                ('code', models.CharField(blank=True, help_text='Unique code for the tehsil.', max_length=20, verbose_name='Tehsil Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tehsils', to='core.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'Tehsil',
                'verbose_name_plural': 'Tehsils',
                'ordering': ['district__division__name', 'district__name', 'name'],
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('name', models.CharField(help_text='e.g., "TMA Town-1 Peshawar" or "LCB Peshawar"', max_length=150, verbose_name='Organization Name')),
                ('org_type', models.CharField(choices=[('TMA', 'Tehsil Municipal Administration'), ('TOWN', 'Town Municipal Administration'), ('LCB', 'Local Council Board'), ('LGD', 'Local Government Department')], default='TMA', max_length=10, verbose_name='Organization Type')),
                ('ddo_code', models.CharField(blank=True, help_text='Drawing & Disbursing Officer Code (unique per organization).', max_length=50, null=True, unique=True, verbose_name='DDO Code')),
                ('pla_account_no', models.CharField(blank=True, help_text='Personal Ledger Account number at AG Office.', max_length=50, verbose_name='PLA Account No')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Bank Name')),
                ('bank_account_no', models.CharField(blank=True, max_length=50, verbose_name='Bank Account No')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('tehsil', models.ForeignKey(blank=True, help_text='Geographic location. Null for LCB/LGD.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.tehsil', verbose_name='Tehsil')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='TMA',
        ),
    ]
