# Generated by Django 4.2.25 on 2026-01-26 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_budgethead_public_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_multi_tenancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='bank_account_no',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='bank_name',
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active in the system.', verbose_name='Is Active')),
                ('bank_name', models.CharField(help_text='Name of the bank (e.g., "National Bank of Pakistan").', max_length=100, verbose_name='Bank Name')),
                ('branch_code', models.CharField(blank=True, help_text='Bank branch code.', max_length=20, verbose_name='Branch Code')),
                ('account_number', models.CharField(help_text='Bank account number (must be unique).', max_length=50, unique=True, verbose_name='Account Number')),
                ('title', models.CharField(help_text='Account title/name as per bank records.', max_length=150, verbose_name='Account Title')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('gl_code', models.ForeignKey(help_text='Link to BudgetHead (Asset account in General Ledger).', on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='finance.budgethead', verbose_name='GL Code')),
                ('organization', models.ForeignKey(help_text='The TMA/Organization that owns this account.', on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='core.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['organization__name', 'bank_name', 'account_number'],
                'indexes': [models.Index(fields=['organization'], name='core_bankac_organiz_161934_idx'), models.Index(fields=['account_number'], name='core_bankac_account_19405a_idx')],
            },
        ),
    ]
