# Generated by Django 4.2.25 on 2026-01-31 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_remove_organization_bank_account_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('title', models.CharField(help_text='Short notification title.', max_length=200, verbose_name='Title')),
                ('message', models.TextField(help_text='Detailed notification message.', verbose_name='Message')),
                ('link', models.CharField(blank=True, help_text='URL to the document or page requiring action.', max_length=500, verbose_name='Link')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read.', verbose_name='Is Read')),
                ('category', models.CharField(choices=[('WORKFLOW', 'Workflow'), ('SYSTEM', 'System'), ('ALERT', 'Alert')], default='WORKFLOW', max_length=20, verbose_name='Category')),
                ('icon', models.CharField(default='bi-bell', help_text='Bootstrap icon class for display.', max_length=50, verbose_name='Icon')),
                ('recipient', models.ForeignKey(help_text='User who should receive this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='core_notifi_recipie_aeffaf_idx'), models.Index(fields=['recipient', '-created_at'], name='core_notifi_recipie_4d7e73_idx')],
            },
        ),
    ]
