# Generated by Django 4.2.25 on 2026-02-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='enforce_department_isolation',
            field=models.BooleanField(default=False, help_text='When enabled, users can only access data (bills, budgets, etc.) from their assigned department. Disable to allow all users to see all departments within this organization. Note: TMO, Finance Officers, and Superusers always have full access.', verbose_name='Enforce Department Isolation'),
        ),
    ]
