# Generated by Django 4.2.25 on 2026-01-27 14:51

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_remove_organization_bank_account_no_and_more'),
        ('budgeting', '0012_phase3_pension_budget_execution'),
        ('finance', '0006_budgethead_is_system_head_budgethead_system_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active in the system.', verbose_name='Is Active')),
                ('name', models.CharField(help_text='Full name of the vendor/contractor/employee.', max_length=200, verbose_name='Payee Name')),
                ('cnic_ntn', models.CharField(blank=True, help_text='CNIC for individuals or NTN for companies.', max_length=20, verbose_name='CNIC/NTN')),
                ('address', models.TextField(blank=True, help_text='Full mailing address.', verbose_name='Address')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, help_text='Contact email address.', max_length=254, verbose_name='Email')),
                ('bank_name', models.CharField(blank=True, help_text='Name of the bank for payment.', max_length=100, verbose_name='Bank Name')),
                ('bank_account', models.CharField(blank=True, help_text='Bank account number for payment.', max_length=50, verbose_name='Bank Account')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Payee',
                'verbose_name_plural': 'Payees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('bill_date', models.DateField(help_text='Date on the vendor invoice.', verbose_name='Bill Date')),
                ('bill_number', models.CharField(help_text="Vendor's invoice or reference number.", max_length=50, verbose_name='Bill/Invoice Number')),
                ('description', models.TextField(help_text='Description of goods/services.', verbose_name='Description')),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Total bill amount before tax deduction.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Gross Amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax deducted (Income Tax + GST).', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax Amount')),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount payable to vendor (Gross - Tax).', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Net Amount')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=15, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected At')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_bills', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('budget_head', models.ForeignKey(help_text='Expense head to charge.', on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='finance.budgethead', verbose_name='Budget Head')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='budgeting.fiscalyear', verbose_name='Fiscal Year')),
                ('liability_voucher', models.OneToOneField(blank=True, help_text='GL voucher recording the liability.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill', to='finance.voucher', verbose_name='Liability Voucher')),
                ('organization', models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='expenditure.payee', verbose_name='Payee')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_bills', to=settings.AUTH_USER_MODEL, verbose_name='Rejected By')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_bills', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'ordering': ['-bill_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('cheque_number', models.CharField(max_length=20, verbose_name='Cheque Number')),
                ('cheque_date', models.DateField(verbose_name='Cheque Date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount (should equal bill net_amount).', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('is_posted', models.BooleanField(default=False, help_text='Whether payment has been posted to GL.', verbose_name='Is Posted')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted At')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.bankaccount', verbose_name='Bank Account')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='expenditure.bill', verbose_name='Bill')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization')),
                ('payment_voucher', models.OneToOneField(blank=True, help_text='GL voucher recording the payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='finance.voucher', verbose_name='Payment Voucher')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_payments', to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-cheque_date', '-created_at'],
                'indexes': [models.Index(fields=['organization'], name='expenditure_organiz_590959_idx'), models.Index(fields=['cheque_date'], name='expenditure_cheque__cb8df2_idx'), models.Index(fields=['is_posted'], name='expenditure_is_post_ead530_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payee',
            index=models.Index(fields=['organization', 'is_active'], name='expenditure_organiz_244d25_idx'),
        ),
        migrations.AddIndex(
            model_name='payee',
            index=models.Index(fields=['name'], name='expenditure_name_f9a61d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payee',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['organization', 'fiscal_year'], name='expenditure_organiz_7578ef_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['status'], name='expenditure_status_1b817a_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['bill_date'], name='expenditure_bill_da_f20dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['payee'], name='expenditure_payee_i_392a54_idx'),
        ),
    ]
