# Generated by Django 4.2.25 on 2026-01-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0003_create_billline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('MARKED_FOR_AUDIT', 'Marked for Audit'), ('AUDITED', 'Audited'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned for Corrections')], default='DRAFT', max_length=32, verbose_name='Status'),
        ),
    ]
