# Generated by Django 4.2.25 on 2026-02-04 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenditure', '0009_add_salary_bill_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='audited_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when bill was pre-audited by Finance Officer.', null=True, verbose_name='Audited At'),
        ),
        migrations.AddField(
            model_name='bill',
            name='audited_by',
            field=models.ForeignKey(blank=True, help_text='Finance Officer who pre-audited this bill.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audited_bills', to=settings.AUTH_USER_MODEL, verbose_name='Audited By'),
        ),
        migrations.AddField(
            model_name='bill',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when bill was verified by TO Finance/Accountant.', null=True, verbose_name='Verified At'),
        ),
        migrations.AddField(
            model_name='bill',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='TO Finance/Accountant who verified this bill.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_bills', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
    ]
