# Generated by Django 4.2.25 on 2026-02-06 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_globalhead_applicable_functions'),
        ('expenditure', '0010_add_audit_trail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='default_budget_head',
            field=models.ForeignKey(blank=True, help_text='Default budget head to use when creating bills for this payee. For example, PESCO → Electricity, PSO → POL.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.budgethead', verbose_name='Default Budget Head'),
        ),
    ]
