# Generated by Django 4.2.25 on 2026-02-06 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_globalhead_applicable_functions'),
        ('expenditure', '0011_payee_default_budget_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payee',
            name='default_budget_head',
        ),
        migrations.AddField(
            model_name='payee',
            name='default_global_head',
            field=models.ForeignKey(blank=True, help_text='Default expense type for this payee (e.g., PESCO → Electricity, PSO → POL). The system will automatically select the correct budget head based on your department.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.globalhead', verbose_name='Default Expense Type'),
        ),
    ]
