# Generated by Django 4.2.25 on 2026-02-06 17:20

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenditure', '0012_remove_payee_default_budget_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='income_tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Income tax withheld under Section 153.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Income Tax (FBR)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='sales_tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sales tax withheld (1/5th or whole).', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sales Tax (FBR/KPRA)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='stamp_duty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stamp duty for works contracts (1% of contract value).', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stamp Duty (Provincial)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='transaction_type',
            field=models.CharField(choices=[('GOODS', 'Supply of Goods'), ('SERVICES', 'Services'), ('WORKS', 'Works Contracts')], default='SERVICES', help_text='Type of transaction determines applicable tax rates.', max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AddField(
            model_name='payee',
            name='entity_type',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('INDIVIDUAL', 'Individual/AOP')], default='INDIVIDUAL', help_text='Company or Individual/AOP for tax rate determination.', max_length=20, verbose_name='Entity Type'),
        ),
        migrations.AddField(
            model_name='payee',
            name='tax_status',
            field=models.CharField(choices=[('FILER', 'Active Filer'), ('NON_FILER', 'Non-Filer'), ('EXEMPT', 'Tax Exempt')], default='NON_FILER', help_text='Filer status as per FBR Active Taxpayers List.', max_length=20, verbose_name='Tax Status'),
        ),
        migrations.AddField(
            model_name='payee',
            name='tax_status_verified_date',
            field=models.DateField(blank=True, help_text='Last date when tax status was verified from FBR list.', null=True, verbose_name='Tax Status Verified Date'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax deducted (Income Tax + Sales Tax + Stamp Duty).', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Tax Amount'),
        ),
        migrations.CreateModel(
            name='BillTaxOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('field_name', models.CharField(choices=[('income_tax_amount', 'Income Tax'), ('sales_tax_amount', 'Sales Tax'), ('stamp_duty_amount', 'Stamp Duty')], max_length=50, verbose_name='Tax Field')),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='System Calculated Value')),
                ('overridden_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Manual Override Value')),
                ('reason', models.TextField(help_text='Explain why the system calculation was incorrect.', verbose_name='Reason for Override')),
                ('overridden_at', models.DateTimeField(auto_now_add=True, verbose_name='Override Timestamp')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_overrides', to='expenditure.bill', verbose_name='Bill')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('overridden_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Overridden By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Bill Tax Override',
                'verbose_name_plural': 'Bill Tax Overrides',
                'ordering': ['-overridden_at'],
                'indexes': [models.Index(fields=['bill'], name='expenditure_bill_id_b7c63c_idx'), models.Index(fields=['overridden_at'], name='expenditure_overrid_205fb2_idx')],
            },
        ),
    ]
