# Generated by Django 4.2.25 on 2026-02-06 17:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0013_add_tax_withholding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRateConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('tax_year', models.CharField(help_text='Fiscal year for these rates (e.g., "2025-26")', max_length=10, unique=True, verbose_name='Tax Year')),
                ('effective_from', models.DateField(help_text='Date from which these rates become active', verbose_name='Effective From')),
                ('effective_to', models.DateField(blank=True, help_text='Date until which these rates are valid (leave blank for indefinite)', null=True, verbose_name='Effective To')),
                ('is_active', models.BooleanField(default=False, help_text='Only one configuration can be active at a time', verbose_name='Is Active')),
                ('goods_filer_company', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='Income tax rate for goods supplied by active filer companies (e.g., 0.0500 for 5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Goods - Active Filer (Company)')),
                ('goods_filer_individual', models.DecimalField(decimal_places=4, default=Decimal('0.0550'), help_text='Income tax rate for goods supplied by active filer individuals', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Goods - Active Filer (Individual)')),
                ('goods_nonfiler_company', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), help_text='Income tax rate for goods supplied by non-filer companies', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Goods - Non-Filer (Company)')),
                ('goods_nonfiler_individual', models.DecimalField(decimal_places=4, default=Decimal('0.1100'), help_text='Income tax rate for goods supplied by non-filer individuals', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Goods - Non-Filer (Individual)')),
                ('services_filer', models.DecimalField(decimal_places=4, default=Decimal('0.1500'), help_text='Income tax rate for services by active filers', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Services - Active Filer')),
                ('services_nonfiler', models.DecimalField(decimal_places=4, default=Decimal('0.3000'), help_text='Income tax rate for services by non-filers', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Services - Non-Filer')),
                ('works_filer_company', models.DecimalField(decimal_places=4, default=Decimal('0.0750'), help_text='Income tax rate for works contracts by active filer companies', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Works - Active Filer (Company)')),
                ('works_filer_individual', models.DecimalField(decimal_places=4, default=Decimal('0.0800'), help_text='Income tax rate for works contracts by active filer individuals', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Works - Active Filer (Individual)')),
                ('works_nonfiler_company', models.DecimalField(decimal_places=4, default=Decimal('0.1500'), help_text='Income tax rate for works contracts by non-filer companies', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Works - Non-Filer (Company)')),
                ('works_nonfiler_individual', models.DecimalField(decimal_places=4, default=Decimal('0.1600'), help_text='Income tax rate for works contracts by non-filer individuals', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Works - Non-Filer (Individual)')),
                ('sales_tax_goods_filer', models.DecimalField(decimal_places=4, default=Decimal('0.2000'), help_text='Withholding rate for goods (1/5th = 0.2000)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Sales Tax Withholding - Goods (Filer)')),
                ('sales_tax_goods_nonfiler', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Withholding rate for goods (whole = 1.0000)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Sales Tax Withholding - Goods (Non-Filer)')),
                ('sales_tax_services_filer', models.DecimalField(decimal_places=4, default=Decimal('0.5000'), help_text='Withholding rate for services (50% = 0.5000)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Sales Tax Withholding - Services (Filer)')),
                ('sales_tax_services_nonfiler', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Withholding rate for services (whole = 1.0000)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Sales Tax Withholding - Services (Non-Filer)')),
                ('sales_tax_works', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Withholding rate for works (whole = 1.0000, regardless of filer status)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Sales Tax Withholding - Works')),
                ('stamp_duty_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), help_text='Stamp duty rate for works contracts (1% = 0.0100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Stamp Duty Rate')),
                ('standard_sales_tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1800'), help_text='Default sales tax rate for calculation (18% = 0.1800)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Standard Sales Tax Rate')),
                ('notes', models.TextField(blank=True, help_text='Reference to FBR/KPRA notification or any special notes', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Tax Rate Configuration',
                'verbose_name_plural': 'Tax Rate Configurations',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['is_active'], name='expenditure_is_acti_fd96c7_idx'), models.Index(fields=['effective_from', 'effective_to'], name='expenditure_effecti_6747cd_idx')],
            },
        ),
    ]
