# Generated by Django 6.0.1 on 2026-02-07 21:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0014_add_tax_rate_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='sales_tax_invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GST amount shown on vendor invoice. Leave blank to auto-calculate at 18%.', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sales Tax on Invoice'),
        ),
    ]
