# Generated by Django 6.0.1 on 2026-01-24 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cnic', models.CharField(help_text='13-digit National Identity Card number (e.g., 12345-1234567-1).', max_length=15, unique=True, verbose_name='CNIC')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('role', models.CharField(choices=[('DA', 'Dealing Assistant (Maker)'), ('AC', 'Accountant (Checker)'), ('TMO', 'Tehsil Municipal Officer (Approver)'), ('TOF', 'Tehsil Officer Finance'), ('LCB', 'LCB Finance Officer'), ('CSH', 'Cashier'), ('ADM', 'System Administrator')], default='DA', help_text='User role in the TMA hierarchy.', max_length=5, verbose_name='Role')),
                ('designation', models.CharField(blank=True, help_text='Official job title (e.g., Junior Clerk, Superintendent).', max_length=100, verbose_name='Designation')),
                ('department', models.CharField(blank=True, help_text='Associated department or wing.', max_length=100, verbose_name='Department')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last Name')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
