# Generated by Django 6.0.1 on 2026-01-24 19:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID'),
        ),
    ]
