# Generated by Django 6.0.1 on 2026-01-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_multi_tenancy'),
        ('users', '0003_alter_customuser_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='TMA this user belongs to. Null for LCB/LGD oversight staff.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.organization', verbose_name='Organization'),
        ),
    ]
