# Generated by Django 4.2.25 on 2026-01-28 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_multi_tenancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('DA', 'Dealing Assistant (Maker)'), ('AC', 'Accountant (Checker)'), ('TMO', 'Tehsil Municipal Officer (Approver)'), ('TOF', 'Tehsil Officer Finance'), ('LCB', 'LCB Finance Officer'), ('CSH', 'Cashier'), ('ADM', 'System Administrator')], default='DA', help_text='DEPRECATED: Use roles field instead. Kept for migration.', max_length=5, verbose_name='Role (Deprecated)'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for the role.', max_length=100, verbose_name='Role Name')),
                ('code', models.SlugField(help_text='Unique identifier code (e.g., TMO, ACCOUNTANT).', unique=True, verbose_name='Role Code')),
                ('description', models.TextField(blank=True, help_text='Detailed description of role responsibilities.', verbose_name='Description')),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted by users.', verbose_name='System Role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(help_text='Associated Django Group for permissions.', on_delete=django.db.models.deletion.CASCADE, related_name='cfms_role', to='auth.group', verbose_name='Django Group')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles assigned to this user.', related_name='users', to='users.role', verbose_name='Roles'),
        ),
    ]
