# Generated by Django 6.0.1 on 2026-01-27 19:08

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgeting', '0012_phase3_pension_budget_execution'),
        ('core', '0005_remove_organization_bank_account_no_and_more'),
        ('finance', '0006_budgethead_is_system_head_budgethead_system_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active in the system.', verbose_name='Is Active')),
                ('name', models.CharField(help_text='Full name of the citizen/entity.', max_length=200, verbose_name='Payer Name')),
                ('cnic_ntn', models.CharField(blank=True, help_text='CNIC for individuals or NTN for companies.', max_length=20, verbose_name='CNIC/NTN')),
                ('contact_no', models.CharField(blank=True, help_text='Phone/mobile number.', max_length=20, verbose_name='Contact Number')),
                ('address', models.TextField(blank=True, help_text='Full mailing address.', verbose_name='Address')),
                ('email', models.EmailField(blank=True, help_text='Contact email address.', max_length=254, verbose_name='Email')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Payer',
                'verbose_name_plural': 'Payers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RevenueDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('challan_no', models.CharField(help_text='Unique demand/challan number.', max_length=50, verbose_name='Challan Number')),
                ('issue_date', models.DateField(help_text='Date demand was issued.', verbose_name='Issue Date')),
                ('due_date', models.DateField(help_text='Payment due date.', verbose_name='Due Date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount due.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Demand Amount')),
                ('period_description', models.CharField(blank=True, help_text='Period covered (e.g., "Jan 2026 Rent", "Q1 2026 License Fee").', max_length=100, verbose_name='Period Description')),
                ('description', models.TextField(blank=True, help_text='Additional notes or description.', verbose_name='Description')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15, verbose_name='Status')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted At')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Cancellation Reason')),
                ('accrual_voucher', models.OneToOneField(blank=True, help_text='GL voucher recording the receivable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_demand', to='finance.voucher', verbose_name='Accrual Voucher')),
                ('budget_head', models.ForeignKey(help_text='Revenue type/head for this demand.', on_delete=django.db.models.deletion.PROTECT, related_name='revenue_demands', to='finance.budgethead', verbose_name='Revenue Head')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_demands', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled By')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_demands', to='budgeting.fiscalyear', verbose_name='Fiscal Year')),
                ('organization', models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='revenue.payer', verbose_name='Payer')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_demands', to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Revenue Demand',
                'verbose_name_plural': 'Revenue Demands',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('receipt_date', models.DateField(help_text='Date payment was received.', verbose_name='Receipt Date')),
                ('receipt_no', models.CharField(help_text='Unique receipt number.', max_length=50, verbose_name='Receipt Number')),
                ('instrument_type', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online Transfer'), ('DD', 'Demand Draft'), ('PO', 'Pay Order')], default='CASH', max_length=10, verbose_name='Instrument Type')),
                ('instrument_no', models.CharField(blank=True, help_text='Cheque number or transaction reference.', max_length=50, verbose_name='Instrument Number')),
                ('amount_received', models.DecimalField(decimal_places=2, help_text='Amount collected.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount Received')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes.', verbose_name='Remarks')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15, verbose_name='Status')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted At')),
                ('bank_account', models.ForeignKey(help_text='Bank account receiving the payment.', on_delete=django.db.models.deletion.PROTECT, related_name='revenue_collections', to='core.bankaccount', verbose_name='Bank Account')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_collections', to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
                ('receipt_voucher', models.OneToOneField(blank=True, help_text='GL voucher recording the receipt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_collection', to='finance.voucher', verbose_name='Receipt Voucher')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='revenue.revenuedemand', verbose_name='Demand')),
            ],
            options={
                'verbose_name': 'Revenue Collection',
                'verbose_name_plural': 'Revenue Collections',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payer',
            index=models.Index(fields=['organization', 'is_active'], name='revenue_pay_organiz_3867dc_idx'),
        ),
        migrations.AddIndex(
            model_name='payer',
            index=models.Index(fields=['name'], name='revenue_pay_name_14e0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='payer',
            index=models.Index(fields=['cnic_ntn'], name='revenue_pay_cnic_nt_6108e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payer',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='revenuedemand',
            index=models.Index(fields=['organization', 'fiscal_year'], name='revenue_rev_organiz_845c09_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuedemand',
            index=models.Index(fields=['status'], name='revenue_rev_status_dc1872_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuedemand',
            index=models.Index(fields=['issue_date'], name='revenue_rev_issue_d_9cd1bb_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuedemand',
            index=models.Index(fields=['payer'], name='revenue_rev_payer_i_6b16b0_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuedemand',
            index=models.Index(fields=['challan_no'], name='revenue_rev_challan_34437f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='revenuedemand',
            unique_together={('organization', 'fiscal_year', 'challan_no')},
        ),
        migrations.AddIndex(
            model_name='revenuecollection',
            index=models.Index(fields=['organization', 'receipt_date'], name='revenue_rev_organiz_5a0119_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuecollection',
            index=models.Index(fields=['status'], name='revenue_rev_status_d090d0_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuecollection',
            index=models.Index(fields=['demand'], name='revenue_rev_demand__80b09b_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuecollection',
            index=models.Index(fields=['receipt_no'], name='revenue_rev_receipt_c10d01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='revenuecollection',
            unique_together={('organization', 'receipt_no')},
        ),
    ]
