# Generated by Django 4.2.25 on 2026-02-07 13:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueCollectionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], max_length=20, verbose_name='Action')),
                ('old_status', models.CharField(blank=True, max_length=15, verbose_name='Old Status')),
                ('new_status', models.CharField(blank=True, max_length=15, verbose_name='New Status')),
                ('changed_fields', models.JSONField(blank=True, default=dict, verbose_name='Changed Fields')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name': 'Revenue Collection Audit',
                'verbose_name_plural': 'Revenue Collection Audits',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueDemandAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], max_length=20, verbose_name='Action')),
                ('old_status', models.CharField(blank=True, max_length=15, verbose_name='Old Status')),
                ('new_status', models.CharField(blank=True, max_length=15, verbose_name='New Status')),
                ('changed_fields', models.JSONField(blank=True, default=dict, help_text='Dictionary of field names and their new values.', verbose_name='Changed Fields')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client identifier.', verbose_name='User Agent')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes about this change.', verbose_name='Remarks')),
            ],
            options={
                'verbose_name': 'Revenue Demand Audit',
                'verbose_name_plural': 'Revenue Demand Audits',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AlterField(
            model_name='payer',
            name='cnic_ntn',
            field=models.CharField(blank=True, help_text='CNIC for individuals or NTN for companies.', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid CNIC (XXXXX-XXXXXXX-X) or NTN (XXXXXXX-X).', regex='^(\\d{5}-\\d{7}-\\d{1}|\\d{13}|\\d{7}-\\d{1})$')], verbose_name='CNIC/NTN'),
        ),
        migrations.AlterField(
            model_name='revenuecollection',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, help_text='Amount collected.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('9999999999999.99'))], verbose_name='Amount Received'),
        ),
        migrations.AlterField(
            model_name='revenuedemand',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount due.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('9999999999999.99'))], verbose_name='Demand Amount'),
        ),
        migrations.AddIndex(
            model_name='revenuecollection',
            index=models.Index(fields=['posted_at'], name='revenue_rev_posted__9c809d_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuecollection',
            index=models.Index(fields=['bank_account'], name='revenue_rev_bank_ac_940b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuedemand',
            index=models.Index(fields=['budget_head'], name='revenue_rev_budget__bde5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuedemand',
            index=models.Index(fields=['posted_at'], name='revenue_rev_posted__99372e_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuedemand',
            index=models.Index(fields=['due_date'], name='revenue_rev_due_dat_9be729_idx'),
        ),
        migrations.AddField(
            model_name='revenuedemandaudit',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_demand_audits', to=settings.AUTH_USER_MODEL, verbose_name='Changed By'),
        ),
        migrations.AddField(
            model_name='revenuedemandaudit',
            name='demand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='revenue.revenuedemand', verbose_name='Demand'),
        ),
        migrations.AddField(
            model_name='revenuecollectionaudit',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_collection_audits', to=settings.AUTH_USER_MODEL, verbose_name='Changed By'),
        ),
        migrations.AddField(
            model_name='revenuecollectionaudit',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='revenue.revenuecollection', verbose_name='Collection'),
        ),
        migrations.AddIndex(
            model_name='revenuedemandaudit',
            index=models.Index(fields=['demand', '-changed_at'], name='revenue_rev_demand__158458_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuedemandaudit',
            index=models.Index(fields=['changed_by', '-changed_at'], name='revenue_rev_changed_4de298_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuedemandaudit',
            index=models.Index(fields=['action', '-changed_at'], name='revenue_rev_action_6f50d5_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuecollectionaudit',
            index=models.Index(fields=['collection', '-changed_at'], name='revenue_rev_collect_a3a62a_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuecollectionaudit',
            index=models.Index(fields=['changed_by', '-changed_at'], name='revenue_rev_changed_e83b05_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuecollectionaudit',
            index=models.Index(fields=['action', '-changed_at'], name='revenue_rev_action_7fe9d1_idx'),
        ),
    ]
