# Generated by Django 4.2.25 on 2026-02-07 13:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_revenuecollectionaudit_revenuedemandaudit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuecollection',
            name='penalty_collected',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Late payment penalty collected.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999999999.99'))], verbose_name='Penalty Collected'),
        ),
        migrations.AddField(
            model_name='revenuedemand',
            name='apply_penalty',
            field=models.BooleanField(default=False, help_text='Whether to calculate penalty for late payment.', verbose_name='Apply Late Payment Penalty'),
        ),
        migrations.AddField(
            model_name='revenuedemand',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated late payment penalty.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999999999.99'))], verbose_name='Penalty Amount'),
        ),
        migrations.AddField(
            model_name='revenuedemand',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Daily penalty rate as percentage of principal amount.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Penalty Rate (% per day)'),
        ),
        migrations.AlterField(
            model_name='revenuecollection',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, help_text='Principal amount collected against demand.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('9999999999999.99'))], verbose_name='Amount Received (Principal)'),
        ),
        migrations.AlterField(
            model_name='revenuedemand',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Principal demand amount (excluding penalty).', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('9999999999999.99'))], verbose_name='Demand Amount'),
        ),
    ]
