# Generated by Django 4.2.25 on 2026-02-07 13:59

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revenue', '0003_revenuecollection_penalty_collected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuedemand',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=0, help_text='Number of days after due date before penalty starts (0 = no grace period).', validators=[django.core.validators.MaxValueValidator(365)], verbose_name='Grace Period (Days)'),
        ),
        migrations.AddField(
            model_name='revenuedemand',
            name='max_penalty_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Maximum penalty as percentage of principal amount (e.g., 50 = penalty cannot exceed 50% of principal).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('500.00'))], verbose_name='Max Penalty (% of Principal)'),
        ),
        migrations.AddField(
            model_name='revenuedemand',
            name='penalty_waived',
            field=models.BooleanField(default=False, help_text='Whether penalty has been waived by management.', verbose_name='Penalty Waived'),
        ),
        migrations.AddField(
            model_name='revenuedemand',
            name='waived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waived At'),
        ),
        migrations.AddField(
            model_name='revenuedemand',
            name='waived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_demand_penalties', to=settings.AUTH_USER_MODEL, verbose_name='Waived By'),
        ),
        migrations.AddField(
            model_name='revenuedemand',
            name='waiver_reason',
            field=models.TextField(blank=True, verbose_name='Waiver Reason'),
        ),
    ]
