# Generated by Django 4.2.25 on 2026-01-24 19:08

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('year_name', models.CharField(help_text='Display name for the fiscal year (e.g., "2026-27").', max_length=20, unique=True, verbose_name='Fiscal Year')),
                ('start_date', models.DateField(help_text='First day of the fiscal year (July 1).', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='Last day of the fiscal year (June 30).', verbose_name='End Date')),
                ('is_active', models.BooleanField(default=False, help_text='Whether budget entry window is currently open.', verbose_name='Budget Entry Active')),
                ('is_locked', models.BooleanField(default=False, help_text='Whether budget is finalized and locked for edits.', verbose_name='Budget Locked')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('VERIFIED', 'Verified by Accountant'), ('APPROVED', 'Approved by TMO'), ('LOCKED', 'Locked (Finalized)')], default='DRAFT', max_length=15, verbose_name='Status')),
                ('sae_number', models.CharField(blank=True, help_text='Unique identifier for Schedule of Authorized Expenditure.', max_length=50, verbose_name='SAE Number')),
                ('sae_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='SAE Generated At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Fiscal Year',
                'verbose_name_plural': 'Fiscal Years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SAERecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('sae_number', models.CharField(max_length=50, unique=True, verbose_name='SAE Number')),
                ('total_receipts', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Receipts')),
                ('total_expenditure', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Expenditure')),
                ('contingency_reserve', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Contingency Reserve (2%)')),
                ('approval_date', models.DateTimeField(auto_now_add=True, verbose_name='Approval Date')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='sae_documents/', verbose_name='PDF Document')),
                ('is_authenticated', models.BooleanField(default=False, help_text='Whether the SAE has been digitally signed by Nazim.', verbose_name='Authenticated by Nazim')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_saes', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('fiscal_year', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sae_record', to='budgeting.fiscalyear', verbose_name='Fiscal Year')),
            ],
            options={
                'verbose_name': 'SAE Record',
                'verbose_name_plural': 'SAE Records',
                'ordering': ['-approval_date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleOfEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('department', models.CharField(help_text='Name of the department or administrative wing.', max_length=100, verbose_name='Department/Wing')),
                ('designation', models.CharField(help_text='Post title (e.g., Junior Clerk, Superintendent).', max_length=100, verbose_name='Designation')),
                ('bps_scale', models.PositiveSmallIntegerField(help_text='Basic Pay Scale grade (1-22).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(22)], verbose_name='BPS Grade')),
                ('sanctioned_posts', models.PositiveIntegerField(default=0, help_text='Number of approved/authorized positions.', verbose_name='Sanctioned Posts')),
                ('occupied_posts', models.PositiveIntegerField(default=0, help_text='Number of currently filled positions.', verbose_name='Occupied Posts')),
                ('annual_salary', models.DecimalField(decimal_places=2, help_text='Annual salary cost per position including allowances.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Annual Salary per Post')),
                ('is_pugf', models.BooleanField(default=False, help_text='Whether this is a Provincial cadre (PUGF) post.', verbose_name='PUGF Post')),
                ('budget_head', models.ForeignKey(help_text='Linked salary head (A01*).', on_delete=django.db.models.deletion.PROTECT, related_name='establishment_entries', to='finance.budgethead', verbose_name='Salary Budget Head')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establishment_schedule', to='budgeting.fiscalyear', verbose_name='Fiscal Year')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Schedule of Establishment',
                'verbose_name_plural': 'Schedule of Establishment Entries',
                'ordering': ['fiscal_year', 'department', '-bps_scale'],
                'unique_together': {('fiscal_year', 'department', 'designation', 'bps_scale')},
            },
        ),
        migrations.CreateModel(
            name='QuarterlyRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1 (July-September)'), ('Q2', 'Q2 (October-December)'), ('Q3', 'Q3 (January-March)'), ('Q4', 'Q4 (April-June)')], max_length=2, verbose_name='Quarter')),
                ('release_date', models.DateField(help_text='Date when the quarterly release was processed.', verbose_name='Release Date')),
                ('is_released', models.BooleanField(default=False, help_text='Whether the quarterly funds have been released.', verbose_name='Released')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Released Amount')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarterly_releases', to='budgeting.fiscalyear', verbose_name='Fiscal Year')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Quarterly Release',
                'verbose_name_plural': 'Quarterly Releases',
                'ordering': ['fiscal_year', 'quarter'],
                'unique_together': {('fiscal_year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('original_allocation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Initially approved budget amount.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Original Allocation')),
                ('revised_allocation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current allocation after re-appropriations.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Revised Allocation')),
                ('released_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount currently available for spending.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Released Amount')),
                ('spent_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual expenditure posted to date.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Spent Amount')),
                ('previous_year_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Last year actual for comparison.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Previous Year Actual')),
                ('current_year_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current year budget for comparison.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Current Year Budget')),
                ('remarks', models.TextField(blank=True, help_text='Justification for significant changes.', verbose_name='Remarks')),
                ('budget_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.budgethead', verbose_name='Budget Head')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='budgeting.fiscalyear', verbose_name='Fiscal Year')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Budget Allocation',
                'verbose_name_plural': 'Budget Allocations',
                'ordering': ['fiscal_year', 'budget_head__pifra_object'],
                'indexes': [models.Index(fields=['fiscal_year', 'budget_head'], name='budgeting_b_fiscal__a4640b_idx')],
                'unique_together': {('fiscal_year', 'budget_head')},
            },
        ),
    ]
