# Generated by Django 6.0.1 on 2026-01-24 19:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0004_alter_budgetallocation_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetallocation',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID'),
        ),
        migrations.AlterField(
            model_name='quarterlyrelease',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID'),
        ),
        migrations.AlterField(
            model_name='saerecord',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID'),
        ),
        migrations.AlterField(
            model_name='scheduleofestablishment',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID'),
        ),
    ]
