# Generated by Django 6.0.1 on 2026-01-25 12:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0005_alter_budgetallocation_public_id_and_more'),
        ('core', '0004_multi_tenancy'),
        ('finance', '0003_alter_budgethead_public_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('name', models.CharField(help_text='Standard designation name (e.g., Junior Clerk, TMO).', max_length=100, unique=True, verbose_name='Designation Name')),
                ('bps_scale', models.PositiveSmallIntegerField(help_text='Default Basic Pay Scale grade (1-22).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(22)], verbose_name='BPS Grade')),
                ('post_type', models.CharField(choices=[('PUGF', 'PUGF (Provincial)'), ('LOCAL', 'Local (TMA)')], default='LOCAL', help_text='PUGF (Provincial) or LOCAL (TMA) classification.', max_length=10, verbose_name='Post Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Designation Master',
                'verbose_name_plural': 'Designation Masters',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='budgetallocation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='quarterlyrelease',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleofestablishment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='quarterlyrelease',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='saerecord',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='scheduleofestablishment',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('VERIFIED', 'Verified by TO Finance'), ('RECOMMENDED', 'Recommended by TMO (Pending LCB)'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Current approval status in the workflow.', max_length=15, verbose_name='Approval Status'),
        ),
        migrations.AddField(
            model_name='scheduleofestablishment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='scheduleofestablishment',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='TMO (for Local) or LCB (for PUGF) who approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_establishments', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='scheduleofestablishment',
            name='designation_name',
            field=models.CharField(default='', help_text='Post title (e.g., Junior Clerk, Superintendent).', max_length=100, verbose_name='Designation Name'),
        ),
        migrations.AddField(
            model_name='scheduleofestablishment',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='scheduleofestablishment',
            name='post_type',
            field=models.CharField(choices=[('PUGF', 'PUGF (Provincial)'), ('LOCAL', 'Local (TMA)')], default='LOCAL', help_text='PUGF requires LCB approval; LOCAL requires TMO approval.', max_length=10, verbose_name='Post Type'),
        ),
        migrations.AddField(
            model_name='scheduleofestablishment',
            name='recommended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recommended At'),
        ),
        migrations.AddField(
            model_name='scheduleofestablishment',
            name='recommended_by',
            field=models.ForeignKey(blank=True, help_text='TMO who recommended (for PUGF posts).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_establishments', to=settings.AUTH_USER_MODEL, verbose_name='Recommended By'),
        ),
        migrations.AddField(
            model_name='scheduleofestablishment',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='year_name',
            field=models.CharField(help_text='Display name for the fiscal year (e.g., "2026-27").', max_length=20, verbose_name='Fiscal Year'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetallocation',
            unique_together={('organization', 'fiscal_year', 'budget_head')},
        ),
        migrations.AlterUniqueTogether(
            name='fiscalyear',
            unique_together={('organization', 'year_name')},
        ),
        migrations.AlterUniqueTogether(
            name='quarterlyrelease',
            unique_together={('organization', 'fiscal_year', 'quarter')},
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['organization'], name='budgeting_b_organiz_521dcd_idx'),
        ),
        migrations.AlterField(
            model_name='scheduleofestablishment',
            name='designation',
            field=models.ForeignKey(blank=True, help_text='Link to master designation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='establishment_entries', to='budgeting.designationmaster', verbose_name='Designation'),
        ),
        migrations.RemoveField(
            model_name='scheduleofestablishment',
            name='is_pugf',
        ),
        migrations.AlterUniqueTogether(
            name='scheduleofestablishment',
            unique_together={('organization', 'fiscal_year', 'department', 'designation_name', 'bps_scale')},
        ),
    ]
