# Generated by Django 6.0.1 on 2026-01-25 13:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0006_budget_multitenancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleofestablishment',
            name='establishment_status',
            field=models.CharField(choices=[('SANCTIONED', 'Sanctioned (Existing)'), ('PROPOSED', 'Proposed (New)')], default='SANCTIONED', help_text='SANCTIONED = existing posts, PROPOSED = new requests (SNE).', max_length=15, verbose_name='Establishment Status'),
        ),
        migrations.AddField(
            model_name='scheduleofestablishment',
            name='financial_impact',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-calculated: Initial Pay x 12 x Number of Posts.', max_digits=15, verbose_name='Financial Impact'),
        ),
        migrations.AddField(
            model_name='scheduleofestablishment',
            name='justification',
            field=models.TextField(blank=True, help_text='Required for PROPOSED posts. Explain why new posts are needed.', verbose_name='Justification'),
        ),
    ]
