# Generated by Django 4.2.25 on 2026-01-25 16:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0007_sne_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPSSalaryScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('bps_grade', models.PositiveSmallIntegerField(help_text='Basic Pay Scale grade (1-22).', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(22)], verbose_name='BPS Grade')),
                ('basic_pay_initial', models.DecimalField(decimal_places=2, help_text='Starting monthly basic pay for this grade.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Initial Basic Pay')),
                ('basic_pay_max', models.DecimalField(decimal_places=2, help_text='Maximum monthly basic pay after all increments.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Maximum Basic Pay')),
                ('annual_increment', models.DecimalField(decimal_places=2, help_text='Yearly increment amount.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Annual Increment')),
                ('allowance_percentage', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Percentage of basic pay for allowances (default 50%).', max_digits=5, verbose_name='Allowance Percentage')),
                ('effective_date', models.DateField(help_text='Date from which this pay scale is effective.', verbose_name='Effective Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'BPS Salary Scale',
                'verbose_name_plural': 'BPS Salary Scales',
                'ordering': ['bps_grade'],
            },
        ),
        migrations.AddField(
            model_name='scheduleofestablishment',
            name='estimated_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Budget estimate from Smart Calculator (filled + vacant costs + inflation).', max_digits=15, verbose_name='Estimated Budget'),
        ),
        migrations.AddField(
            model_name='scheduleofestablishment',
            name='last_month_bill',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Last month total salary bill from bank advice (for estimation).', max_digits=15, verbose_name='Last Month Bill'),
        ),
    ]
