# Generated by Django 4.2.25 on 2026-01-25 18:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgeting', '0009_add_department_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpssalaryscale',
            name='allowance_percentage',
        ),
        migrations.RemoveField(
            model_name='bpssalaryscale',
            name='basic_pay_initial',
        ),
        migrations.RemoveField(
            model_name='bpssalaryscale',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='bpssalaryscale',
            name='is_active',
        ),
        migrations.AddField(
            model_name='bpssalaryscale',
            name='adhoc_relief_total_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.35'), help_text='Sum of all active Adhoc Reliefs (e.g., 0.35 for 35%)', max_digits=5, verbose_name='Total Adhoc Relief %'),
        ),
        migrations.AddField(
            model_name='bpssalaryscale',
            name='basic_pay_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Initial Basic Pay', max_digits=10, verbose_name='Initial Stage (0)'),
        ),
        migrations.AddField(
            model_name='bpssalaryscale',
            name='conveyance_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Conveyance Allowance'),
        ),
        migrations.AddField(
            model_name='bpssalaryscale',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='bpssalaryscale',
            name='house_rent_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.45'), help_text='e.g., 0.45 for 45% of Initial Pay', max_digits=5, verbose_name='House Rent %'),
        ),
        migrations.AddField(
            model_name='bpssalaryscale',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Medical Allowance'),
        ),
        migrations.AddField(
            model_name='bpssalaryscale',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='bpssalaryscale',
            name='annual_increment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual Increment Amount', max_digits=8, verbose_name='Annual Increment'),
        ),
        migrations.AlterField(
            model_name='bpssalaryscale',
            name='basic_pay_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum Basic Pay', max_digits=10, verbose_name='Last Stage (30)'),
        ),
        migrations.AlterField(
            model_name='bpssalaryscale',
            name='bps_grade',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(22)], verbose_name='BPS Grade'),
        ),
    ]
