# Generated by Django 4.2.25 on 2026-01-26 19:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0010_update_bps_salary_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('name', models.CharField(help_text='Full name of the employee.', max_length=150, verbose_name='Employee Name')),
                ('cnic', models.CharField(blank=True, help_text='National ID (e.g., 12345-1234567-1).', max_length=15, verbose_name='CNIC')),
                ('personnel_number', models.CharField(blank=True, help_text='HR personnel/employee number.', max_length=50, verbose_name='Personnel Number')),
                ('is_vacant', models.BooleanField(default=False, help_text='Mark as True if this is a placeholder for a vacant position.', verbose_name='Is Vacant Post')),
                ('current_basic_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current running basic pay (monthly).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Current Basic Pay')),
                ('monthly_allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total monthly allowances (HRA, Medical, Conveyance, Adhoc, etc.).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monthly Allowances')),
                ('annual_increment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected annual increment (added once per year).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Annual Increment Amount')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='budgeting.scheduleofestablishment', verbose_name='Schedule Entry')),
            ],
            options={
                'verbose_name': 'Budget Employee',
                'verbose_name_plural': 'Budget Employees',
                'ordering': ['schedule', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='budgetemployee',
            constraint=models.UniqueConstraint(condition=models.Q(('personnel_number__gt', '')), fields=('schedule', 'personnel_number'), name='unique_schedule_personnel'),
        ),
    ]
