# Generated by Django 4.2.25 on 2026-01-27 03:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0005_alter_budgethead_options_remove_budgethead_fund_id_and_more'),
        ('core', '0005_remove_organization_bank_account_no_and_more'),
        ('budgeting', '0011_budgetemployee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('current_monthly_bill', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total pension bill of June (last month of previous FY).', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Current Monthly Pension Bill')),
                ('expected_increase', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Expected percentage increase in pension (e.g., 10.0 for 10%).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Expected Increase (%)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('LOCKED', 'Locked (Finalized)')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('estimated_monthly_pension', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated: (current_bill * 12 * (1 + increase%)) + new retirees pension.', max_digits=15, verbose_name='Estimated Monthly Pension (A04101)')),
                ('estimated_commutation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated: Sum of all retirees commutation amounts.', max_digits=15, verbose_name='Estimated Commutation (A04102)')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Locked At')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pension_estimates', to='budgeting.fiscalyear', verbose_name='Fiscal Year')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_pension_estimates', to=settings.AUTH_USER_MODEL, verbose_name='Locked By')),
                ('organization', models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Pension Estimate',
                'verbose_name_plural': 'Pension Estimates',
                'ordering': ['-fiscal_year__start_date'],
                'unique_together': {('organization', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='SupplementaryGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Additional budget amount to be granted.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('reference_no', models.CharField(help_text='Government order or reference number.', max_length=50, verbose_name='Reference/Order No')),
                ('date', models.DateField(help_text='Date of supplementary grant order.', verbose_name='Date')),
                ('description', models.TextField(help_text='Justification for supplementary budget.', verbose_name='Description')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_supplementary_grants', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('budget_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplementary_grants', to='finance.budgethead', verbose_name='Budget Head')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplementary_grants', to='budgeting.fiscalyear', verbose_name='Fiscal Year')),
                ('organization', models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Supplementary Grant',
                'verbose_name_plural': 'Supplementary Grants',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RetiringEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('retirement_date', models.DateField(verbose_name='Retirement Date')),
                ('monthly_pension_amount', models.DecimalField(decimal_places=2, help_text='Expected monthly pension payout.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monthly Pension Amount')),
                ('commutation_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lump sum commutation payment.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Commutation Amount')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiring_employees', to='budgeting.pensionestimate', verbose_name='Pension Estimate')),
            ],
            options={
                'verbose_name': 'Retiring Employee',
                'verbose_name_plural': 'Retiring Employees',
                'ordering': ['retirement_date'],
            },
        ),
        migrations.CreateModel(
            name='Reappropriation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to transfer.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('reference_no', models.CharField(help_text='Authorization reference number.', max_length=50, verbose_name='Reference/Order No')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(help_text='Justification for re-appropriation.', verbose_name='Description')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reappropriations', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reappropriations', to='budgeting.fiscalyear', verbose_name='Fiscal Year')),
                ('from_head', models.ForeignKey(help_text='Source head to transfer budget from.', on_delete=django.db.models.deletion.PROTECT, related_name='reappropriations_out', to='finance.budgethead', verbose_name='From Budget Head')),
                ('organization', models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization')),
                ('to_head', models.ForeignKey(help_text='Destination head to transfer budget to.', on_delete=django.db.models.deletion.PROTECT, related_name='reappropriations_in', to='finance.budgethead', verbose_name='To Budget Head')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Re-appropriation',
                'verbose_name_plural': 'Re-appropriations',
                'ordering': ['-date'],
            },
        ),
    ]
