# Generated by Django 4.2.25 on 2026-01-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0012_phase3_pension_budget_execution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetallocation',
            options={'ordering': ['fiscal_year', 'budget_head__global_head__code'], 'verbose_name': 'Budget Allocation', 'verbose_name_plural': 'Budget Allocations'},
        ),
    ]
