# Generated by Django 6.0.1 on 2026-01-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0013_alter_budgetallocation_options'),
        ('finance', '0015_alter_budgethead_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Short code for the department (e.g., INFRA, FIN).', max_length=10, verbose_name='Department Code'),
        ),
        migrations.AddField(
            model_name='department',
            name='related_functions',
            field=models.ManyToManyField(blank=True, help_text='Accounting functions (Element 3) managed by this wing.', related_name='departments', to='finance.functioncode', verbose_name='Related Functions'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Name of the Department or Wing (e.g., Infrastructure, Finance).', max_length=100, unique=True, verbose_name='Department Name'),
        ),
    ]
