# Generated by Django 4.2.25 on 2026-02-01 10:26

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_globalhead_system_code'),
        ('expenditure', '0005_alter_bill_status'),
        ('budgeting', '0014_department_code_department_related_functions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSalaryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, help_text='Initial budget allocated based on employee strength', max_digits=15)),
                ('consumed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount consumed through approved bills', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_budgets', to='budgeting.department')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dept_salary_budgets', to='budgeting.fiscalyear')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dept_salary_budgets', to='finance.fund')),
                ('global_head', models.ForeignKey(help_text='Salary account code (A01151, A01202, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='dept_salary_budgets', to='finance.globalhead')),
            ],
            options={
                'db_table': 'budgeting_department_salary_budget',
            },
        ),
        migrations.CreateModel(
            name='SalaryBillConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text="Amount consumed from this department's budget", max_digits=15)),
                ('employee_count', models.IntegerField(help_text='Number of employees from this department in the bill')),
                ('is_reversed', models.BooleanField(default=False, help_text='True if bill was cancelled and budget released')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_consumptions', to='expenditure.bill')),
                ('department_budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='budgeting.departmentsalarybudget')),
            ],
            options={
                'db_table': 'budgeting_salary_bill_consumption',
                'indexes': [models.Index(fields=['bill', 'department_budget'], name='budgeting_s_bill_id_5266de_idx'), models.Index(fields=['created_at'], name='budgeting_s_created_ed72b9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='departmentsalarybudget',
            index=models.Index(fields=['department', 'fiscal_year'], name='budgeting_d_departm_93784a_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentsalarybudget',
            index=models.Index(fields=['fiscal_year', 'global_head'], name='budgeting_d_fiscal__2c951e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentsalarybudget',
            unique_together={('department', 'fiscal_year', 'fund', 'global_head')},
        ),
    ]
