# Generated by Django 4.2.25 on 2026-02-01 11:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0015_departmentsalarybudget_salarybillconsumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetemployee',
            name='adhoc_relief_2024',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Adhoc relief allowance (50% of basic).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Adhoc Relief 2024'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='conveyance_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly conveyance as per BPS.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Conveyance Allowance'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='entertainment_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Entertainment allowance for senior officers.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Entertainment Allowance'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='gpf_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='General Provident Fund monthly deduction.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='GPF Contribution'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='house_rent_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='HRA as per BPS scale.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='House Rent Allowance'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='income_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly income tax deduction.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Income Tax'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='joining_date',
            field=models.DateField(blank=True, help_text='Date of joining service.', null=True, verbose_name='Joining Date'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='last_increment_date',
            field=models.DateField(blank=True, help_text='Date when last increment was applied.', null=True, verbose_name='Last Increment Date'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Medical allowance as per BPS.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Medical Allowance'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='remarks',
            field=models.TextField(blank=True, help_text='Any additional notes.', verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='special_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Any special/additional allowance.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Special Allowance'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='utility_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Utility allowance for senior officers.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Utility Allowance'),
        ),
        migrations.AlterField(
            model_name='budgetemployee',
            name='annual_increment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected annual increment (added once per year to basic).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Annual Increment Amount'),
        ),
        migrations.AlterField(
            model_name='budgetemployee',
            name='monthly_allowances',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deprecated: Use individual allowance fields instead.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monthly Allowances (Legacy)'),
        ),
    ]
