# Generated by Django 4.2.25 on 2026-02-01 14:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0016_budgetemployee_adhoc_relief_2024_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budgetemployee',
            name='unique_schedule_personnel',
        ),
        migrations.RemoveField(
            model_name='budgetemployee',
            name='adhoc_relief_2024',
        ),
        migrations.RemoveField(
            model_name='budgetemployee',
            name='annual_increment_amount',
        ),
        migrations.RemoveField(
            model_name='budgetemployee',
            name='cnic',
        ),
        migrations.RemoveField(
            model_name='budgetemployee',
            name='conveyance_allowance',
        ),
        migrations.RemoveField(
            model_name='budgetemployee',
            name='current_basic_pay',
        ),
        migrations.RemoveField(
            model_name='budgetemployee',
            name='entertainment_allowance',
        ),
        migrations.RemoveField(
            model_name='budgetemployee',
            name='gpf_contribution',
        ),
        migrations.RemoveField(
            model_name='budgetemployee',
            name='house_rent_allowance',
        ),
        migrations.RemoveField(
            model_name='budgetemployee',
            name='income_tax',
        ),
        migrations.RemoveField(
            model_name='budgetemployee',
            name='last_increment_date',
        ),
        migrations.RemoveField(
            model_name='budgetemployee',
            name='medical_allowance',
        ),
        migrations.RemoveField(
            model_name='budgetemployee',
            name='monthly_allowances',
        ),
        migrations.RemoveField(
            model_name='budgetemployee',
            name='personnel_number',
        ),
        migrations.RemoveField(
            model_name='budgetemployee',
            name='special_allowance',
        ),
        migrations.RemoveField(
            model_name='budgetemployee',
            name='utility_allowance',
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='ara_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.22'), help_text='ARA (Allowance, Relief & Adjustment) percentage on Running Basic. Default 22%.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='ARA Percentage'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='bps',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BPS-1'), (2, 'BPS-2'), (3, 'BPS-3'), (4, 'BPS-4'), (5, 'BPS-5'), (6, 'BPS-6'), (7, 'BPS-7'), (8, 'BPS-8'), (9, 'BPS-9'), (10, 'BPS-10'), (11, 'BPS-11'), (12, 'BPS-12'), (13, 'BPS-13'), (14, 'BPS-14'), (15, 'BPS-15'), (16, 'BPS-16'), (17, 'BPS-17'), (18, 'BPS-18'), (19, 'BPS-19'), (20, 'BPS-20'), (21, 'BPS-21'), (22, 'BPS-22')], default=1, help_text='Basic Pay Scale grade (1-22).', verbose_name='BPS Grade'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='city_category',
            field=models.CharField(choices=[('LARGE', 'Large Cities'), ('OTHER', 'Other Cities / Towns')], default='OTHER', help_text='City classification for HRA calculation (Large/Other).', max_length=10, verbose_name='City Category'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='dra_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed amount based on 2017 Basic Pay scale. Does NOT increase with increments.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='DRA (Disparity Reduction Allowance)'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='father_name',
            field=models.CharField(blank=True, help_text="Father's name for official records.", max_length=150, verbose_name="Father's Name"),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='is_govt_accommodation',
            field=models.BooleanField(default=False, help_text='If true, HRA = 0.', verbose_name='Occupies Government Accommodation'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='is_house_hiring',
            field=models.BooleanField(default=False, help_text='If true, HRA = 0.', verbose_name='Drawing House Hiring Benefit'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='running_basic',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running Basic = Min Basic + earned increments (capped at Max). This is the primary pay component.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Running Basic Pay'),
        ),
    ]
