# Generated by Django 4.2.25 on 2026-02-01 14:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0017_remove_budgetemployee_unique_schedule_personnel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpssalaryscale',
            name='adhoc_relief_total_percent',
        ),
        migrations.RemoveField(
            model_name='bpssalaryscale',
            name='house_rent_percent',
        ),
        migrations.AddField(
            model_name='bpssalaryscale',
            name='adhoc_relief_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.22'), help_text='Percentage applied to Running Basic Pay (default 0.22 = 22%)', max_digits=5, verbose_name='ARA % (Adhoc Relief)'),
        ),
        migrations.AddField(
            model_name='bpssalaryscale',
            name='house_rent_large_cities',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed HRA amount for large cities (e.g., Peshawar, Islamabad)', max_digits=8, verbose_name='HRA - Large Cities'),
        ),
        migrations.AddField(
            model_name='bpssalaryscale',
            name='house_rent_other_cities',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed HRA amount for other cities/towns', max_digits=8, verbose_name='HRA - Other Cities'),
        ),
    ]
