# Generated by Django 4.2.25 on 2026-02-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0018_remove_bpssalaryscale_adhoc_relief_total_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetemployee',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth for age and retirement calculations.', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='designation',
            field=models.CharField(blank=True, help_text='Job designation/position title.', max_length=150, verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='qualification',
            field=models.CharField(blank=True, help_text='Educational qualification (e.g., B.A., M.A., M.B.B.S.).', max_length=150, verbose_name='Qualification'),
        ),
    ]
