# Generated by Django 4.2.25 on 2026-02-01 15:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0019_budgetemployee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetemployee',
            name='ara_percentage',
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='ara_2022_auto_calculated',
            field=models.BooleanField(default=False, help_text='Flag: True if ARA 2022 was auto-calculated (new entrant). Needs verification.', verbose_name='ARA 2022 Auto-Calculated'),
        ),
        migrations.AddField(
            model_name='budgetemployee',
            name='frozen_ara_2022_input',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text="Frozen amount from employee's last pay slip. If left blank, will auto-calculate as 15% of Min BPS.", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='ARA 2022 (From Last Slip)'),
        ),
        migrations.AlterField(
            model_name='budgetemployee',
            name='running_basic',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current Running Basic from last pay slip. Used as basis for all ARA calculations.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Current Running Basic Pay'),
        ),
    ]
