# Generated by Django 4.2.25 on 2026-02-01 15:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0020_remove_budgetemployee_ara_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetemployee',
            name='expected_salary_increase_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage increase for next year budget estimates (0-100). Used for salary projections.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Expected Salary Increase %'),
        ),
    ]
