# Generated by Django 4.2.25 on 2026-02-05 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_notification'),
        ('budgeting', '0023_add_default_function_and_usage_notes'),
    ]

    operations = [
        # 1. Add New Fields to FiscalYear (so we can use them in RunPython)
        migrations.AddField(
            model_name='fiscalyear',
            name='is_planning_active',
            field=models.BooleanField(default=False, help_text='Whether TMAs can create/edit budget proposals (May-June).', verbose_name='Planning Window Open'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='is_revision_active',
            field=models.BooleanField(default=False, help_text='Whether TMAs can revise budgets (March cycle).', verbose_name='Revision Window Open'),
        ),

        # 2. Create BudgetProposal Model
        migrations.CreateModel(
            name='BudgetProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for external reference.', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COUNCIL_APPROVED', 'Council Approved'), ('SUBMITTED', 'Submitted to LCB'), ('UNDER_REVIEW', 'Under LCB Review'), ('SANCTIONED', 'Sanctioned by LCB'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active for Transactions'), ('CLOSED', 'Closed (Year End)')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('is_locked', models.BooleanField(default=False, help_text='Whether this budget proposal is locked for editing.', verbose_name='Is Locked')),
                ('council_resolution_no', models.CharField(blank=True, help_text='Resolution number from Tehsil Council.', max_length=50, verbose_name='Council Resolution No.')),
                ('council_resolution_date', models.DateField(blank=True, null=True, verbose_name='Council Resolution Date')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('sanctioned_at', models.DateTimeField(blank=True, null=True, verbose_name='Sanctioned At')),
                ('sae_number', models.CharField(blank=True, help_text='Schedule of Authorized Expenditure number.', max_length=50, verbose_name='SAE Number')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='budgeting.fiscalyear', verbose_name='Fiscal Year')),
                ('organization', models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization')),
                ('sanctioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctioned_budgets', to=settings.AUTH_USER_MODEL, verbose_name='Sanctioned By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Budget Proposal',
                'verbose_name_plural': 'Budget Proposals',
                'ordering': ['-fiscal_year__start_date', 'organization__name'],
                'indexes': [models.Index(fields=['organization', 'fiscal_year'], name='budgeting_b_organiz_aa2bc1_idx'), models.Index(fields=['status'], name='budgeting_b_status_70fd22_idx')],
                'unique_together': {('organization', 'fiscal_year')},
            },
        ),
    ]
