# Generated by Django 6.0.1 on 2026-02-05 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0026_finalize_global_fiscal_year'),
        ('core', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetemployee',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The TMA/Organization that owns this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='core.organization', verbose_name='Organization'),
        ),
    ]
