# Generated by Django 4.2.25 on 2026-02-09 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0027_budgetemployee_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetallocation',
            options={'ordering': ['fiscal_year'], 'verbose_name': 'Budget Allocation', 'verbose_name_plural': 'Budget Allocations'},
        ),
    ]
